apiVersion: v1
kind: Service
metadata:
  name: {{ include "novastor.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novastor.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  clusterIP: None
  selector:
    {{- include "novastor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  ports:
    - name: grpc
      port: 9100
      protocol: TCP
      targetPort: grpc
    - name: metrics
      port: 9101
      protocol: TCP
      targetPort: metrics
