apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: novastor.csi.novastor.io
  labels:
    {{- include "novastor.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
