apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "novastor.fullname" . }}-meta
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novastor.labels" . | nindent 4 }}
    app.kubernetes.io/component: meta
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "novastor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: meta
