apiVersion: v1
kind: Secret
metadata:
  name: {{ include "novastor.fullname" . }}-s3gw
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novastor.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3gw
type: Opaque
data:
  {{- if .Values.s3gw.accessKey }}
  access-key: {{ .Values.s3gw.accessKey | b64enc }}
  {{- else }}
  access-key: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
  {{- if .Values.s3gw.secretKey }}
  secret-key: {{ .Values.s3gw.secretKey | b64enc }}
  {{- else }}
  secret-key: {{ randAlphaNum 40 | b64enc }}
  {{- end }}
