{{- $secretName := printf "%s-s3gw" (include "novastor.fullname" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novastor.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3gw
type: Opaque
data:
  {{- if .Values.s3gw.accessKey }}
  access-key: {{ .Values.s3gw.accessKey | b64enc }}
  {{- else if and $existing $existing.data (index $existing.data "access-key") }}
  access-key: {{ index $existing.data "access-key" }}
  {{- else }}
  access-key: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
  {{- if .Values.s3gw.secretKey }}
  secret-key: {{ .Values.s3gw.secretKey | b64enc }}
  {{- else if and $existing $existing.data (index $existing.data "secret-key") }}
  secret-key: {{ index $existing.data "secret-key" }}
  {{- else }}
  secret-key: {{ randAlphaNum 40 | b64enc }}
  {{- end }}
