apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name | default "novastor-block" }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageClass.isDefault | default false }}"
provisioner: novastor.csi.novastor.io
parameters:
  pool: {{ .Values.storageClass.pool | default "nvme-replicated" }}
  dataProtection: {{ .Values.storageClass.dataProtection | default "replication" }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy | default "Delete" }}
allowVolumeExpansion: true
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode | default "WaitForFirstConsumer" }}
