{{- if include "novastor.tls.enabled" . }}
{{- if not .Values.global.tls.externalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "novastor.tls.volumeName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novastor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.tls.ca.certPEM }}
  ca.crt: {{ .Values.global.tls.ca.certPEM | b64enc }}
  {{- else }}
  ca.crt: ""
  {{- end }}
  {{- if .Values.global.tls.ca.keyPEM }}
  ca.key: {{ .Values.global.tls.ca.keyPEM | b64enc }}
  {{- else }}
  ca.key: ""
  {{- end }}
  {{- if .Values.global.tls.server.certPEM }}
  server.crt: {{ .Values.global.tls.server.certPEM | b64enc }}
  {{- else }}
  server.crt: ""
  {{- end }}
  {{- if .Values.global.tls.server.keyPEM }}
  server.key: {{ .Values.global.tls.server.keyPEM | b64enc }}
  {{- else }}
  server.key: ""
  {{- end }}
  {{- if .Values.global.tls.client.certPEM }}
  client.crt: {{ .Values.global.tls.client.certPEM | b64enc }}
  {{- else }}
  client.crt: ""
  {{- end }}
  {{- if .Values.global.tls.client.keyPEM }}
  client.key: {{ .Values.global.tls.client.keyPEM | b64enc }}
  {{- else }}
  client.key: ""
  {{- end }}
{{- end }}
{{- end }}
