// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: api/proto/dataplane/dataplane.proto

package dataplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataplaneService_CreateAioBdev_FullMethodName       = "/dataplane.DataplaneService/CreateAioBdev"
	DataplaneService_CreateMallocBdev_FullMethodName    = "/dataplane.DataplaneService/CreateMallocBdev"
	DataplaneService_CreateLvolStore_FullMethodName     = "/dataplane.DataplaneService/CreateLvolStore"
	DataplaneService_CreateLvol_FullMethodName          = "/dataplane.DataplaneService/CreateLvol"
	DataplaneService_DeleteBdev_FullMethodName          = "/dataplane.DataplaneService/DeleteBdev"
	DataplaneService_ListBdevs_FullMethodName           = "/dataplane.DataplaneService/ListBdevs"
	DataplaneService_GetBdevInfo_FullMethodName         = "/dataplane.DataplaneService/GetBdevInfo"
	DataplaneService_ListLvolStores_FullMethodName      = "/dataplane.DataplaneService/ListLvolStores"
	DataplaneService_InitTransport_FullMethodName       = "/dataplane.DataplaneService/InitTransport"
	DataplaneService_CreateNvmfTarget_FullMethodName    = "/dataplane.DataplaneService/CreateNvmfTarget"
	DataplaneService_DeleteNvmfTarget_FullMethodName    = "/dataplane.DataplaneService/DeleteNvmfTarget"
	DataplaneService_SetAnaState_FullMethodName         = "/dataplane.DataplaneService/SetAnaState"
	DataplaneService_GetAnaState_FullMethodName         = "/dataplane.DataplaneService/GetAnaState"
	DataplaneService_ListSubsystems_FullMethodName      = "/dataplane.DataplaneService/ListSubsystems"
	DataplaneService_ExportBdev_FullMethodName          = "/dataplane.DataplaneService/ExportBdev"
	DataplaneService_ConnectInitiator_FullMethodName    = "/dataplane.DataplaneService/ConnectInitiator"
	DataplaneService_DisconnectInitiator_FullMethodName = "/dataplane.DataplaneService/DisconnectInitiator"
	DataplaneService_CreateReplicaBdev_FullMethodName   = "/dataplane.DataplaneService/CreateReplicaBdev"
	DataplaneService_ReplicaStatus_FullMethodName       = "/dataplane.DataplaneService/ReplicaStatus"
	DataplaneService_InitChunkStore_FullMethodName      = "/dataplane.DataplaneService/InitChunkStore"
	DataplaneService_ChunkStoreStats_FullMethodName     = "/dataplane.DataplaneService/ChunkStoreStats"
	DataplaneService_WriteChunk_FullMethodName          = "/dataplane.DataplaneService/WriteChunk"
	DataplaneService_ReadChunk_FullMethodName           = "/dataplane.DataplaneService/ReadChunk"
	DataplaneService_DeleteChunk_FullMethodName         = "/dataplane.DataplaneService/DeleteChunk"
	DataplaneService_ChunkExists_FullMethodName         = "/dataplane.DataplaneService/ChunkExists"
	DataplaneService_ListChunks_FullMethodName          = "/dataplane.DataplaneService/ListChunks"
	DataplaneService_GarbageCollect_FullMethodName      = "/dataplane.DataplaneService/GarbageCollect"
	DataplaneService_InitBackend_FullMethodName         = "/dataplane.DataplaneService/InitBackend"
	DataplaneService_CreateVolume_FullMethodName        = "/dataplane.DataplaneService/CreateVolume"
	DataplaneService_DeleteVolume_FullMethodName        = "/dataplane.DataplaneService/DeleteVolume"
	DataplaneService_SetVolumePolicy_FullMethodName     = "/dataplane.DataplaneService/SetVolumePolicy"
	DataplaneService_UpdateTopology_FullMethodName      = "/dataplane.DataplaneService/UpdateTopology"
	DataplaneService_GetVersion_FullMethodName          = "/dataplane.DataplaneService/GetVersion"
	DataplaneService_Heartbeat_FullMethodName           = "/dataplane.DataplaneService/Heartbeat"
	DataplaneService_GetChunkMaps_FullMethodName        = "/dataplane.DataplaneService/GetChunkMaps"
	DataplaneService_SyncChunkMaps_FullMethodName       = "/dataplane.DataplaneService/SyncChunkMaps"
)

// DataplaneServiceClient is the client API for DataplaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataplaneService is the single gRPC API between the Go management agent
// and the Rust SPDK dataplane. It replaces ALL JSON-RPC communication.
// See: docs/superpowers/specs/2026-03-15-layered-architecture-design.md
type DataplaneServiceClient interface {
	// CreateAioBdev creates an SPDK AIO bdev backed by a file on the host filesystem.
	CreateAioBdev(ctx context.Context, in *CreateAioBdevRequest, opts ...grpc.CallOption) (*BdevInfo, error)
	// CreateMallocBdev creates an in-memory SPDK Malloc bdev (test mode only).
	CreateMallocBdev(ctx context.Context, in *CreateMallocBdevRequest, opts ...grpc.CallOption) (*BdevInfo, error)
	// CreateLvolStore creates an SPDK lvol store on an existing bdev.
	CreateLvolStore(ctx context.Context, in *CreateLvolStoreRequest, opts ...grpc.CallOption) (*LvolStoreInfo, error)
	// CreateLvol creates a logical volume within an lvol store.
	CreateLvol(ctx context.Context, in *CreateLvolRequest, opts ...grpc.CallOption) (*BdevInfo, error)
	// DeleteBdev removes any SPDK bdev by name.
	DeleteBdev(ctx context.Context, in *DeleteBdevRequest, opts ...grpc.CallOption) (*DeleteBdevResponse, error)
	// ListBdevs returns all registered bdevs.
	ListBdevs(ctx context.Context, in *ListBdevsRequest, opts ...grpc.CallOption) (*ListBdevsResponse, error)
	// GetBdevInfo returns detailed info for a single bdev.
	GetBdevInfo(ctx context.Context, in *GetBdevInfoRequest, opts ...grpc.CallOption) (*BdevInfo, error)
	// ListLvolStores returns all lvol stores.
	ListLvolStores(ctx context.Context, in *ListLvolStoresRequest, opts ...grpc.CallOption) (*ListLvolStoresResponse, error)
	// InitTransport initialises the NVMe-oF TCP transport (idempotent).
	InitTransport(ctx context.Context, in *InitTransportRequest, opts ...grpc.CallOption) (*InitTransportResponse, error)
	// CreateNvmfTarget creates an NVMe-oF subsystem with a namespace backed by a bdev.
	CreateNvmfTarget(ctx context.Context, in *CreateNvmfTargetRequest, opts ...grpc.CallOption) (*NvmfTargetInfo, error)
	// DeleteNvmfTarget tears down an NVMe-oF subsystem.
	DeleteNvmfTarget(ctx context.Context, in *DeleteNvmfTargetRequest, opts ...grpc.CallOption) (*DeleteNvmfTargetResponse, error)
	// SetAnaState changes the ANA state for a volume's NVMe-oF target.
	SetAnaState(ctx context.Context, in *SetAnaStateRequest, opts ...grpc.CallOption) (*SetAnaStateResponse, error)
	// GetAnaState returns the current ANA state for a volume's target.
	GetAnaState(ctx context.Context, in *GetAnaStateRequest, opts ...grpc.CallOption) (*GetAnaStateResponse, error)
	// ListSubsystems lists all NVMe-oF subsystems.
	ListSubsystems(ctx context.Context, in *ListSubsystemsRequest, opts ...grpc.CallOption) (*ListSubsystemsResponse, error)
	// ExportBdev exports a named bdev as an NVMe-oF namespace on an existing subsystem.
	ExportBdev(ctx context.Context, in *ExportBdevRequest, opts ...grpc.CallOption) (*ExportBdevResponse, error)
	// ConnectInitiator connects as an NVMe-oF initiator to a remote target.
	ConnectInitiator(ctx context.Context, in *ConnectInitiatorRequest, opts ...grpc.CallOption) (*ConnectInitiatorResponse, error)
	// DisconnectInitiator disconnects from a remote NVMe-oF target.
	DisconnectInitiator(ctx context.Context, in *DisconnectInitiatorRequest, opts ...grpc.CallOption) (*DisconnectInitiatorResponse, error)
	// CreateReplicaBdev creates a composite bdev that fans out writes to local + remote bdevs.
	CreateReplicaBdev(ctx context.Context, in *CreateReplicaBdevRequest, opts ...grpc.CallOption) (*CreateReplicaBdevResponse, error)
	// ReplicaStatus returns health/status of a replica bdev.
	ReplicaStatus(ctx context.Context, in *ReplicaStatusRequest, opts ...grpc.CallOption) (*ReplicaStatusResponse, error)
	// InitChunkStore initialises a chunk store on a bdev with bitmap allocator.
	InitChunkStore(ctx context.Context, in *InitChunkStoreRequest, opts ...grpc.CallOption) (*InitChunkStoreResponse, error)
	// ChunkStoreStats returns capacity/usage statistics for a chunk store.
	ChunkStoreStats(ctx context.Context, in *ChunkStoreStatsRequest, opts ...grpc.CallOption) (*ChunkStoreStatsResponse, error)
	// WriteChunk writes a content-addressed chunk. Client streams data fragments.
	WriteChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteChunkRequest, WriteChunkResponse], error)
	// ReadChunk reads a chunk by ID. Server streams data back.
	ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadChunkResponse], error)
	// DeleteChunk removes a chunk by ID.
	DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error)
	// ChunkExists checks if a chunk ID exists in the store.
	ChunkExists(ctx context.Context, in *ChunkExistsRequest, opts ...grpc.CallOption) (*ChunkExistsResponse, error)
	// ListChunks returns all chunk IDs in the store.
	ListChunks(ctx context.Context, in *ListChunksRequest, opts ...grpc.CallOption) (*ListChunksResponse, error)
	// GarbageCollect removes orphan chunks not referenced by any volume.
	GarbageCollect(ctx context.Context, in *GarbageCollectRequest, opts ...grpc.CallOption) (*GarbageCollectResponse, error)
	// InitBackend initialises a storage backend (raw, lvm, or file).
	InitBackend(ctx context.Context, in *InitBackendRequest, opts ...grpc.CallOption) (*InitBackendResponse, error)
	// CreateVolume creates a volume on a backend.
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	// DeleteVolume deletes a volume from a backend.
	DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error)
	// SetVolumePolicy sets the replication policy for a volume.
	SetVolumePolicy(ctx context.Context, in *SetVolumePolicyRequest, opts ...grpc.CallOption) (*SetVolumePolicyResponse, error)
	// UpdateTopology pushes a full cluster topology snapshot to the dataplane.
	UpdateTopology(ctx context.Context, in *UpdateTopologyRequest, opts ...grpc.CallOption) (*UpdateTopologyResponse, error)
	// GetVersion returns the dataplane version.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// Heartbeat is sent periodically by the Go agent. If the dataplane stops
	// receiving heartbeats, it fences itself (stops accepting writes).
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// --- Metadata Sync ---
	GetChunkMaps(ctx context.Context, in *GetChunkMapsRequest, opts ...grpc.CallOption) (*GetChunkMapsResponse, error)
	// SyncChunkMaps returns all chunk map entries whose generation is strictly
	// greater than since_generation. Used as a periodic safety net to recover
	// any NDP broadcast updates that were missed.
	SyncChunkMaps(ctx context.Context, in *SyncChunkMapsRequest, opts ...grpc.CallOption) (*SyncChunkMapsResponse, error)
}

type dataplaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataplaneServiceClient(cc grpc.ClientConnInterface) DataplaneServiceClient {
	return &dataplaneServiceClient{cc}
}

func (c *dataplaneServiceClient) CreateAioBdev(ctx context.Context, in *CreateAioBdevRequest, opts ...grpc.CallOption) (*BdevInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BdevInfo)
	err := c.cc.Invoke(ctx, DataplaneService_CreateAioBdev_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) CreateMallocBdev(ctx context.Context, in *CreateMallocBdevRequest, opts ...grpc.CallOption) (*BdevInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BdevInfo)
	err := c.cc.Invoke(ctx, DataplaneService_CreateMallocBdev_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) CreateLvolStore(ctx context.Context, in *CreateLvolStoreRequest, opts ...grpc.CallOption) (*LvolStoreInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LvolStoreInfo)
	err := c.cc.Invoke(ctx, DataplaneService_CreateLvolStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) CreateLvol(ctx context.Context, in *CreateLvolRequest, opts ...grpc.CallOption) (*BdevInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BdevInfo)
	err := c.cc.Invoke(ctx, DataplaneService_CreateLvol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) DeleteBdev(ctx context.Context, in *DeleteBdevRequest, opts ...grpc.CallOption) (*DeleteBdevResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBdevResponse)
	err := c.cc.Invoke(ctx, DataplaneService_DeleteBdev_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) ListBdevs(ctx context.Context, in *ListBdevsRequest, opts ...grpc.CallOption) (*ListBdevsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBdevsResponse)
	err := c.cc.Invoke(ctx, DataplaneService_ListBdevs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) GetBdevInfo(ctx context.Context, in *GetBdevInfoRequest, opts ...grpc.CallOption) (*BdevInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BdevInfo)
	err := c.cc.Invoke(ctx, DataplaneService_GetBdevInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) ListLvolStores(ctx context.Context, in *ListLvolStoresRequest, opts ...grpc.CallOption) (*ListLvolStoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLvolStoresResponse)
	err := c.cc.Invoke(ctx, DataplaneService_ListLvolStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) InitTransport(ctx context.Context, in *InitTransportRequest, opts ...grpc.CallOption) (*InitTransportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitTransportResponse)
	err := c.cc.Invoke(ctx, DataplaneService_InitTransport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) CreateNvmfTarget(ctx context.Context, in *CreateNvmfTargetRequest, opts ...grpc.CallOption) (*NvmfTargetInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NvmfTargetInfo)
	err := c.cc.Invoke(ctx, DataplaneService_CreateNvmfTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) DeleteNvmfTarget(ctx context.Context, in *DeleteNvmfTargetRequest, opts ...grpc.CallOption) (*DeleteNvmfTargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNvmfTargetResponse)
	err := c.cc.Invoke(ctx, DataplaneService_DeleteNvmfTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) SetAnaState(ctx context.Context, in *SetAnaStateRequest, opts ...grpc.CallOption) (*SetAnaStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAnaStateResponse)
	err := c.cc.Invoke(ctx, DataplaneService_SetAnaState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) GetAnaState(ctx context.Context, in *GetAnaStateRequest, opts ...grpc.CallOption) (*GetAnaStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnaStateResponse)
	err := c.cc.Invoke(ctx, DataplaneService_GetAnaState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) ListSubsystems(ctx context.Context, in *ListSubsystemsRequest, opts ...grpc.CallOption) (*ListSubsystemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubsystemsResponse)
	err := c.cc.Invoke(ctx, DataplaneService_ListSubsystems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) ExportBdev(ctx context.Context, in *ExportBdevRequest, opts ...grpc.CallOption) (*ExportBdevResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportBdevResponse)
	err := c.cc.Invoke(ctx, DataplaneService_ExportBdev_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) ConnectInitiator(ctx context.Context, in *ConnectInitiatorRequest, opts ...grpc.CallOption) (*ConnectInitiatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectInitiatorResponse)
	err := c.cc.Invoke(ctx, DataplaneService_ConnectInitiator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) DisconnectInitiator(ctx context.Context, in *DisconnectInitiatorRequest, opts ...grpc.CallOption) (*DisconnectInitiatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectInitiatorResponse)
	err := c.cc.Invoke(ctx, DataplaneService_DisconnectInitiator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) CreateReplicaBdev(ctx context.Context, in *CreateReplicaBdevRequest, opts ...grpc.CallOption) (*CreateReplicaBdevResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReplicaBdevResponse)
	err := c.cc.Invoke(ctx, DataplaneService_CreateReplicaBdev_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) ReplicaStatus(ctx context.Context, in *ReplicaStatusRequest, opts ...grpc.CallOption) (*ReplicaStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaStatusResponse)
	err := c.cc.Invoke(ctx, DataplaneService_ReplicaStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) InitChunkStore(ctx context.Context, in *InitChunkStoreRequest, opts ...grpc.CallOption) (*InitChunkStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitChunkStoreResponse)
	err := c.cc.Invoke(ctx, DataplaneService_InitChunkStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) ChunkStoreStats(ctx context.Context, in *ChunkStoreStatsRequest, opts ...grpc.CallOption) (*ChunkStoreStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkStoreStatsResponse)
	err := c.cc.Invoke(ctx, DataplaneService_ChunkStoreStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) WriteChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteChunkRequest, WriteChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataplaneService_ServiceDesc.Streams[0], DataplaneService_WriteChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteChunkRequest, WriteChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneService_WriteChunkClient = grpc.ClientStreamingClient[WriteChunkRequest, WriteChunkResponse]

func (c *dataplaneServiceClient) ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataplaneService_ServiceDesc.Streams[1], DataplaneService_ReadChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadChunkRequest, ReadChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneService_ReadChunkClient = grpc.ServerStreamingClient[ReadChunkResponse]

func (c *dataplaneServiceClient) DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChunkResponse)
	err := c.cc.Invoke(ctx, DataplaneService_DeleteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) ChunkExists(ctx context.Context, in *ChunkExistsRequest, opts ...grpc.CallOption) (*ChunkExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkExistsResponse)
	err := c.cc.Invoke(ctx, DataplaneService_ChunkExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) ListChunks(ctx context.Context, in *ListChunksRequest, opts ...grpc.CallOption) (*ListChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChunksResponse)
	err := c.cc.Invoke(ctx, DataplaneService_ListChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) GarbageCollect(ctx context.Context, in *GarbageCollectRequest, opts ...grpc.CallOption) (*GarbageCollectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GarbageCollectResponse)
	err := c.cc.Invoke(ctx, DataplaneService_GarbageCollect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) InitBackend(ctx context.Context, in *InitBackendRequest, opts ...grpc.CallOption) (*InitBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitBackendResponse)
	err := c.cc.Invoke(ctx, DataplaneService_InitBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, DataplaneService_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVolumeResponse)
	err := c.cc.Invoke(ctx, DataplaneService_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) SetVolumePolicy(ctx context.Context, in *SetVolumePolicyRequest, opts ...grpc.CallOption) (*SetVolumePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVolumePolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneService_SetVolumePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) UpdateTopology(ctx context.Context, in *UpdateTopologyRequest, opts ...grpc.CallOption) (*UpdateTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTopologyResponse)
	err := c.cc.Invoke(ctx, DataplaneService_UpdateTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, DataplaneService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, DataplaneService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) GetChunkMaps(ctx context.Context, in *GetChunkMapsRequest, opts ...grpc.CallOption) (*GetChunkMapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChunkMapsResponse)
	err := c.cc.Invoke(ctx, DataplaneService_GetChunkMaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) SyncChunkMaps(ctx context.Context, in *SyncChunkMapsRequest, opts ...grpc.CallOption) (*SyncChunkMapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncChunkMapsResponse)
	err := c.cc.Invoke(ctx, DataplaneService_SyncChunkMaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataplaneServiceServer is the server API for DataplaneService service.
// All implementations must embed UnimplementedDataplaneServiceServer
// for forward compatibility.
//
// DataplaneService is the single gRPC API between the Go management agent
// and the Rust SPDK dataplane. It replaces ALL JSON-RPC communication.
// See: docs/superpowers/specs/2026-03-15-layered-architecture-design.md
type DataplaneServiceServer interface {
	// CreateAioBdev creates an SPDK AIO bdev backed by a file on the host filesystem.
	CreateAioBdev(context.Context, *CreateAioBdevRequest) (*BdevInfo, error)
	// CreateMallocBdev creates an in-memory SPDK Malloc bdev (test mode only).
	CreateMallocBdev(context.Context, *CreateMallocBdevRequest) (*BdevInfo, error)
	// CreateLvolStore creates an SPDK lvol store on an existing bdev.
	CreateLvolStore(context.Context, *CreateLvolStoreRequest) (*LvolStoreInfo, error)
	// CreateLvol creates a logical volume within an lvol store.
	CreateLvol(context.Context, *CreateLvolRequest) (*BdevInfo, error)
	// DeleteBdev removes any SPDK bdev by name.
	DeleteBdev(context.Context, *DeleteBdevRequest) (*DeleteBdevResponse, error)
	// ListBdevs returns all registered bdevs.
	ListBdevs(context.Context, *ListBdevsRequest) (*ListBdevsResponse, error)
	// GetBdevInfo returns detailed info for a single bdev.
	GetBdevInfo(context.Context, *GetBdevInfoRequest) (*BdevInfo, error)
	// ListLvolStores returns all lvol stores.
	ListLvolStores(context.Context, *ListLvolStoresRequest) (*ListLvolStoresResponse, error)
	// InitTransport initialises the NVMe-oF TCP transport (idempotent).
	InitTransport(context.Context, *InitTransportRequest) (*InitTransportResponse, error)
	// CreateNvmfTarget creates an NVMe-oF subsystem with a namespace backed by a bdev.
	CreateNvmfTarget(context.Context, *CreateNvmfTargetRequest) (*NvmfTargetInfo, error)
	// DeleteNvmfTarget tears down an NVMe-oF subsystem.
	DeleteNvmfTarget(context.Context, *DeleteNvmfTargetRequest) (*DeleteNvmfTargetResponse, error)
	// SetAnaState changes the ANA state for a volume's NVMe-oF target.
	SetAnaState(context.Context, *SetAnaStateRequest) (*SetAnaStateResponse, error)
	// GetAnaState returns the current ANA state for a volume's target.
	GetAnaState(context.Context, *GetAnaStateRequest) (*GetAnaStateResponse, error)
	// ListSubsystems lists all NVMe-oF subsystems.
	ListSubsystems(context.Context, *ListSubsystemsRequest) (*ListSubsystemsResponse, error)
	// ExportBdev exports a named bdev as an NVMe-oF namespace on an existing subsystem.
	ExportBdev(context.Context, *ExportBdevRequest) (*ExportBdevResponse, error)
	// ConnectInitiator connects as an NVMe-oF initiator to a remote target.
	ConnectInitiator(context.Context, *ConnectInitiatorRequest) (*ConnectInitiatorResponse, error)
	// DisconnectInitiator disconnects from a remote NVMe-oF target.
	DisconnectInitiator(context.Context, *DisconnectInitiatorRequest) (*DisconnectInitiatorResponse, error)
	// CreateReplicaBdev creates a composite bdev that fans out writes to local + remote bdevs.
	CreateReplicaBdev(context.Context, *CreateReplicaBdevRequest) (*CreateReplicaBdevResponse, error)
	// ReplicaStatus returns health/status of a replica bdev.
	ReplicaStatus(context.Context, *ReplicaStatusRequest) (*ReplicaStatusResponse, error)
	// InitChunkStore initialises a chunk store on a bdev with bitmap allocator.
	InitChunkStore(context.Context, *InitChunkStoreRequest) (*InitChunkStoreResponse, error)
	// ChunkStoreStats returns capacity/usage statistics for a chunk store.
	ChunkStoreStats(context.Context, *ChunkStoreStatsRequest) (*ChunkStoreStatsResponse, error)
	// WriteChunk writes a content-addressed chunk. Client streams data fragments.
	WriteChunk(grpc.ClientStreamingServer[WriteChunkRequest, WriteChunkResponse]) error
	// ReadChunk reads a chunk by ID. Server streams data back.
	ReadChunk(*ReadChunkRequest, grpc.ServerStreamingServer[ReadChunkResponse]) error
	// DeleteChunk removes a chunk by ID.
	DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error)
	// ChunkExists checks if a chunk ID exists in the store.
	ChunkExists(context.Context, *ChunkExistsRequest) (*ChunkExistsResponse, error)
	// ListChunks returns all chunk IDs in the store.
	ListChunks(context.Context, *ListChunksRequest) (*ListChunksResponse, error)
	// GarbageCollect removes orphan chunks not referenced by any volume.
	GarbageCollect(context.Context, *GarbageCollectRequest) (*GarbageCollectResponse, error)
	// InitBackend initialises a storage backend (raw, lvm, or file).
	InitBackend(context.Context, *InitBackendRequest) (*InitBackendResponse, error)
	// CreateVolume creates a volume on a backend.
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	// DeleteVolume deletes a volume from a backend.
	DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error)
	// SetVolumePolicy sets the replication policy for a volume.
	SetVolumePolicy(context.Context, *SetVolumePolicyRequest) (*SetVolumePolicyResponse, error)
	// UpdateTopology pushes a full cluster topology snapshot to the dataplane.
	UpdateTopology(context.Context, *UpdateTopologyRequest) (*UpdateTopologyResponse, error)
	// GetVersion returns the dataplane version.
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// Heartbeat is sent periodically by the Go agent. If the dataplane stops
	// receiving heartbeats, it fences itself (stops accepting writes).
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// --- Metadata Sync ---
	GetChunkMaps(context.Context, *GetChunkMapsRequest) (*GetChunkMapsResponse, error)
	// SyncChunkMaps returns all chunk map entries whose generation is strictly
	// greater than since_generation. Used as a periodic safety net to recover
	// any NDP broadcast updates that were missed.
	SyncChunkMaps(context.Context, *SyncChunkMapsRequest) (*SyncChunkMapsResponse, error)
	mustEmbedUnimplementedDataplaneServiceServer()
}

// UnimplementedDataplaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataplaneServiceServer struct{}

func (UnimplementedDataplaneServiceServer) CreateAioBdev(context.Context, *CreateAioBdevRequest) (*BdevInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAioBdev not implemented")
}
func (UnimplementedDataplaneServiceServer) CreateMallocBdev(context.Context, *CreateMallocBdevRequest) (*BdevInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMallocBdev not implemented")
}
func (UnimplementedDataplaneServiceServer) CreateLvolStore(context.Context, *CreateLvolStoreRequest) (*LvolStoreInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLvolStore not implemented")
}
func (UnimplementedDataplaneServiceServer) CreateLvol(context.Context, *CreateLvolRequest) (*BdevInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLvol not implemented")
}
func (UnimplementedDataplaneServiceServer) DeleteBdev(context.Context, *DeleteBdevRequest) (*DeleteBdevResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBdev not implemented")
}
func (UnimplementedDataplaneServiceServer) ListBdevs(context.Context, *ListBdevsRequest) (*ListBdevsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBdevs not implemented")
}
func (UnimplementedDataplaneServiceServer) GetBdevInfo(context.Context, *GetBdevInfoRequest) (*BdevInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBdevInfo not implemented")
}
func (UnimplementedDataplaneServiceServer) ListLvolStores(context.Context, *ListLvolStoresRequest) (*ListLvolStoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLvolStores not implemented")
}
func (UnimplementedDataplaneServiceServer) InitTransport(context.Context, *InitTransportRequest) (*InitTransportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitTransport not implemented")
}
func (UnimplementedDataplaneServiceServer) CreateNvmfTarget(context.Context, *CreateNvmfTargetRequest) (*NvmfTargetInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNvmfTarget not implemented")
}
func (UnimplementedDataplaneServiceServer) DeleteNvmfTarget(context.Context, *DeleteNvmfTargetRequest) (*DeleteNvmfTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNvmfTarget not implemented")
}
func (UnimplementedDataplaneServiceServer) SetAnaState(context.Context, *SetAnaStateRequest) (*SetAnaStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAnaState not implemented")
}
func (UnimplementedDataplaneServiceServer) GetAnaState(context.Context, *GetAnaStateRequest) (*GetAnaStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnaState not implemented")
}
func (UnimplementedDataplaneServiceServer) ListSubsystems(context.Context, *ListSubsystemsRequest) (*ListSubsystemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubsystems not implemented")
}
func (UnimplementedDataplaneServiceServer) ExportBdev(context.Context, *ExportBdevRequest) (*ExportBdevResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportBdev not implemented")
}
func (UnimplementedDataplaneServiceServer) ConnectInitiator(context.Context, *ConnectInitiatorRequest) (*ConnectInitiatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectInitiator not implemented")
}
func (UnimplementedDataplaneServiceServer) DisconnectInitiator(context.Context, *DisconnectInitiatorRequest) (*DisconnectInitiatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectInitiator not implemented")
}
func (UnimplementedDataplaneServiceServer) CreateReplicaBdev(context.Context, *CreateReplicaBdevRequest) (*CreateReplicaBdevResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReplicaBdev not implemented")
}
func (UnimplementedDataplaneServiceServer) ReplicaStatus(context.Context, *ReplicaStatusRequest) (*ReplicaStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaStatus not implemented")
}
func (UnimplementedDataplaneServiceServer) InitChunkStore(context.Context, *InitChunkStoreRequest) (*InitChunkStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitChunkStore not implemented")
}
func (UnimplementedDataplaneServiceServer) ChunkStoreStats(context.Context, *ChunkStoreStatsRequest) (*ChunkStoreStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChunkStoreStats not implemented")
}
func (UnimplementedDataplaneServiceServer) WriteChunk(grpc.ClientStreamingServer[WriteChunkRequest, WriteChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WriteChunk not implemented")
}
func (UnimplementedDataplaneServiceServer) ReadChunk(*ReadChunkRequest, grpc.ServerStreamingServer[ReadChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReadChunk not implemented")
}
func (UnimplementedDataplaneServiceServer) DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChunk not implemented")
}
func (UnimplementedDataplaneServiceServer) ChunkExists(context.Context, *ChunkExistsRequest) (*ChunkExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChunkExists not implemented")
}
func (UnimplementedDataplaneServiceServer) ListChunks(context.Context, *ListChunksRequest) (*ListChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChunks not implemented")
}
func (UnimplementedDataplaneServiceServer) GarbageCollect(context.Context, *GarbageCollectRequest) (*GarbageCollectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GarbageCollect not implemented")
}
func (UnimplementedDataplaneServiceServer) InitBackend(context.Context, *InitBackendRequest) (*InitBackendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitBackend not implemented")
}
func (UnimplementedDataplaneServiceServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedDataplaneServiceServer) DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedDataplaneServiceServer) SetVolumePolicy(context.Context, *SetVolumePolicyRequest) (*SetVolumePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVolumePolicy not implemented")
}
func (UnimplementedDataplaneServiceServer) UpdateTopology(context.Context, *UpdateTopologyRequest) (*UpdateTopologyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTopology not implemented")
}
func (UnimplementedDataplaneServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedDataplaneServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDataplaneServiceServer) GetChunkMaps(context.Context, *GetChunkMapsRequest) (*GetChunkMapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunkMaps not implemented")
}
func (UnimplementedDataplaneServiceServer) SyncChunkMaps(context.Context, *SyncChunkMapsRequest) (*SyncChunkMapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncChunkMaps not implemented")
}
func (UnimplementedDataplaneServiceServer) mustEmbedUnimplementedDataplaneServiceServer() {}
func (UnimplementedDataplaneServiceServer) testEmbeddedByValue()                          {}

// UnsafeDataplaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataplaneServiceServer will
// result in compilation errors.
type UnsafeDataplaneServiceServer interface {
	mustEmbedUnimplementedDataplaneServiceServer()
}

func RegisterDataplaneServiceServer(s grpc.ServiceRegistrar, srv DataplaneServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataplaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataplaneService_ServiceDesc, srv)
}

func _DataplaneService_CreateAioBdev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAioBdevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).CreateAioBdev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_CreateAioBdev_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).CreateAioBdev(ctx, req.(*CreateAioBdevRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_CreateMallocBdev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMallocBdevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).CreateMallocBdev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_CreateMallocBdev_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).CreateMallocBdev(ctx, req.(*CreateMallocBdevRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_CreateLvolStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLvolStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).CreateLvolStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_CreateLvolStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).CreateLvolStore(ctx, req.(*CreateLvolStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_CreateLvol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLvolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).CreateLvol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_CreateLvol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).CreateLvol(ctx, req.(*CreateLvolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_DeleteBdev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBdevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).DeleteBdev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_DeleteBdev_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).DeleteBdev(ctx, req.(*DeleteBdevRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_ListBdevs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBdevsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).ListBdevs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_ListBdevs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).ListBdevs(ctx, req.(*ListBdevsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_GetBdevInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBdevInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).GetBdevInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_GetBdevInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).GetBdevInfo(ctx, req.(*GetBdevInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_ListLvolStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLvolStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).ListLvolStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_ListLvolStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).ListLvolStores(ctx, req.(*ListLvolStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_InitTransport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitTransportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).InitTransport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_InitTransport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).InitTransport(ctx, req.(*InitTransportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_CreateNvmfTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNvmfTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).CreateNvmfTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_CreateNvmfTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).CreateNvmfTarget(ctx, req.(*CreateNvmfTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_DeleteNvmfTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNvmfTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).DeleteNvmfTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_DeleteNvmfTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).DeleteNvmfTarget(ctx, req.(*DeleteNvmfTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_SetAnaState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAnaStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).SetAnaState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_SetAnaState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).SetAnaState(ctx, req.(*SetAnaStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_GetAnaState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnaStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).GetAnaState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_GetAnaState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).GetAnaState(ctx, req.(*GetAnaStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_ListSubsystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubsystemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).ListSubsystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_ListSubsystems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).ListSubsystems(ctx, req.(*ListSubsystemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_ExportBdev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportBdevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).ExportBdev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_ExportBdev_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).ExportBdev(ctx, req.(*ExportBdevRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_ConnectInitiator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectInitiatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).ConnectInitiator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_ConnectInitiator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).ConnectInitiator(ctx, req.(*ConnectInitiatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_DisconnectInitiator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectInitiatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).DisconnectInitiator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_DisconnectInitiator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).DisconnectInitiator(ctx, req.(*DisconnectInitiatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_CreateReplicaBdev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReplicaBdevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).CreateReplicaBdev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_CreateReplicaBdev_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).CreateReplicaBdev(ctx, req.(*CreateReplicaBdevRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_ReplicaStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).ReplicaStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_ReplicaStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).ReplicaStatus(ctx, req.(*ReplicaStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_InitChunkStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitChunkStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).InitChunkStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_InitChunkStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).InitChunkStore(ctx, req.(*InitChunkStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_ChunkStoreStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkStoreStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).ChunkStoreStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_ChunkStoreStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).ChunkStoreStats(ctx, req.(*ChunkStoreStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_WriteChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataplaneServiceServer).WriteChunk(&grpc.GenericServerStream[WriteChunkRequest, WriteChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneService_WriteChunkServer = grpc.ClientStreamingServer[WriteChunkRequest, WriteChunkResponse]

func _DataplaneService_ReadChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataplaneServiceServer).ReadChunk(m, &grpc.GenericServerStream[ReadChunkRequest, ReadChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneService_ReadChunkServer = grpc.ServerStreamingServer[ReadChunkResponse]

func _DataplaneService_DeleteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).DeleteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_DeleteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).DeleteChunk(ctx, req.(*DeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_ChunkExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).ChunkExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_ChunkExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).ChunkExists(ctx, req.(*ChunkExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_ListChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).ListChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_ListChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).ListChunks(ctx, req.(*ListChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_GarbageCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GarbageCollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).GarbageCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_GarbageCollect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).GarbageCollect(ctx, req.(*GarbageCollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_InitBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).InitBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_InitBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).InitBackend(ctx, req.(*InitBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).DeleteVolume(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_SetVolumePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVolumePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).SetVolumePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_SetVolumePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).SetVolumePolicy(ctx, req.(*SetVolumePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_UpdateTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).UpdateTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_UpdateTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).UpdateTopology(ctx, req.(*UpdateTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_GetChunkMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChunkMapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).GetChunkMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_GetChunkMaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).GetChunkMaps(ctx, req.(*GetChunkMapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_SyncChunkMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncChunkMapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).SyncChunkMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_SyncChunkMaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).SyncChunkMaps(ctx, req.(*SyncChunkMapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataplaneService_ServiceDesc is the grpc.ServiceDesc for DataplaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataplaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataplane.DataplaneService",
	HandlerType: (*DataplaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAioBdev",
			Handler:    _DataplaneService_CreateAioBdev_Handler,
		},
		{
			MethodName: "CreateMallocBdev",
			Handler:    _DataplaneService_CreateMallocBdev_Handler,
		},
		{
			MethodName: "CreateLvolStore",
			Handler:    _DataplaneService_CreateLvolStore_Handler,
		},
		{
			MethodName: "CreateLvol",
			Handler:    _DataplaneService_CreateLvol_Handler,
		},
		{
			MethodName: "DeleteBdev",
			Handler:    _DataplaneService_DeleteBdev_Handler,
		},
		{
			MethodName: "ListBdevs",
			Handler:    _DataplaneService_ListBdevs_Handler,
		},
		{
			MethodName: "GetBdevInfo",
			Handler:    _DataplaneService_GetBdevInfo_Handler,
		},
		{
			MethodName: "ListLvolStores",
			Handler:    _DataplaneService_ListLvolStores_Handler,
		},
		{
			MethodName: "InitTransport",
			Handler:    _DataplaneService_InitTransport_Handler,
		},
		{
			MethodName: "CreateNvmfTarget",
			Handler:    _DataplaneService_CreateNvmfTarget_Handler,
		},
		{
			MethodName: "DeleteNvmfTarget",
			Handler:    _DataplaneService_DeleteNvmfTarget_Handler,
		},
		{
			MethodName: "SetAnaState",
			Handler:    _DataplaneService_SetAnaState_Handler,
		},
		{
			MethodName: "GetAnaState",
			Handler:    _DataplaneService_GetAnaState_Handler,
		},
		{
			MethodName: "ListSubsystems",
			Handler:    _DataplaneService_ListSubsystems_Handler,
		},
		{
			MethodName: "ExportBdev",
			Handler:    _DataplaneService_ExportBdev_Handler,
		},
		{
			MethodName: "ConnectInitiator",
			Handler:    _DataplaneService_ConnectInitiator_Handler,
		},
		{
			MethodName: "DisconnectInitiator",
			Handler:    _DataplaneService_DisconnectInitiator_Handler,
		},
		{
			MethodName: "CreateReplicaBdev",
			Handler:    _DataplaneService_CreateReplicaBdev_Handler,
		},
		{
			MethodName: "ReplicaStatus",
			Handler:    _DataplaneService_ReplicaStatus_Handler,
		},
		{
			MethodName: "InitChunkStore",
			Handler:    _DataplaneService_InitChunkStore_Handler,
		},
		{
			MethodName: "ChunkStoreStats",
			Handler:    _DataplaneService_ChunkStoreStats_Handler,
		},
		{
			MethodName: "DeleteChunk",
			Handler:    _DataplaneService_DeleteChunk_Handler,
		},
		{
			MethodName: "ChunkExists",
			Handler:    _DataplaneService_ChunkExists_Handler,
		},
		{
			MethodName: "ListChunks",
			Handler:    _DataplaneService_ListChunks_Handler,
		},
		{
			MethodName: "GarbageCollect",
			Handler:    _DataplaneService_GarbageCollect_Handler,
		},
		{
			MethodName: "InitBackend",
			Handler:    _DataplaneService_InitBackend_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _DataplaneService_CreateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _DataplaneService_DeleteVolume_Handler,
		},
		{
			MethodName: "SetVolumePolicy",
			Handler:    _DataplaneService_SetVolumePolicy_Handler,
		},
		{
			MethodName: "UpdateTopology",
			Handler:    _DataplaneService_UpdateTopology_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _DataplaneService_GetVersion_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _DataplaneService_Heartbeat_Handler,
		},
		{
			MethodName: "GetChunkMaps",
			Handler:    _DataplaneService_GetChunkMaps_Handler,
		},
		{
			MethodName: "SyncChunkMaps",
			Handler:    _DataplaneService_SyncChunkMaps_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteChunk",
			Handler:       _DataplaneService_WriteChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadChunk",
			Handler:       _DataplaneService_ReadChunk_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/dataplane/dataplane.proto",
}
