apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: novastor-csi
  labels:
    app.kubernetes.io/name: novastor
    app.kubernetes.io/component: csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: novastor-csi
subjects:
  - kind: ServiceAccount
    name: novastor-csi
    namespace: novastor-system
