// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: api/proto/chunk/chunk.proto

package chunk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkService_PutChunk_FullMethodName    = "/chunk.ChunkService/PutChunk"
	ChunkService_GetChunk_FullMethodName    = "/chunk.ChunkService/GetChunk"
	ChunkService_DeleteChunk_FullMethodName = "/chunk.ChunkService/DeleteChunk"
	ChunkService_HasChunk_FullMethodName    = "/chunk.ChunkService/HasChunk"
)

// ChunkServiceClient is the client API for ChunkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChunkService provides gRPC access to the chunk storage layer.
type ChunkServiceClient interface {
	// PutChunk stores a chunk. The client streams data fragments which the
	// server assembles into a complete chunk.
	PutChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutChunkRequest, PutChunkResponse], error)
	// GetChunk retrieves a chunk. The server streams the chunk data back
	// in fragments.
	GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChunkResponse], error)
	// DeleteChunk removes a chunk from the store.
	DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error)
	// HasChunk checks whether a chunk exists in the store.
	HasChunk(ctx context.Context, in *HasChunkRequest, opts ...grpc.CallOption) (*HasChunkResponse, error)
}

type chunkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkServiceClient(cc grpc.ClientConnInterface) ChunkServiceClient {
	return &chunkServiceClient{cc}
}

func (c *chunkServiceClient) PutChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutChunkRequest, PutChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkService_ServiceDesc.Streams[0], ChunkService_PutChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutChunkRequest, PutChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkService_PutChunkClient = grpc.ClientStreamingClient[PutChunkRequest, PutChunkResponse]

func (c *chunkServiceClient) GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkService_ServiceDesc.Streams[1], ChunkService_GetChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetChunkRequest, GetChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkService_GetChunkClient = grpc.ServerStreamingClient[GetChunkResponse]

func (c *chunkServiceClient) DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkService_DeleteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) HasChunk(ctx context.Context, in *HasChunkRequest, opts ...grpc.CallOption) (*HasChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasChunkResponse)
	err := c.cc.Invoke(ctx, ChunkService_HasChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkServiceServer is the server API for ChunkService service.
// All implementations must embed UnimplementedChunkServiceServer
// for forward compatibility.
//
// ChunkService provides gRPC access to the chunk storage layer.
type ChunkServiceServer interface {
	// PutChunk stores a chunk. The client streams data fragments which the
	// server assembles into a complete chunk.
	PutChunk(grpc.ClientStreamingServer[PutChunkRequest, PutChunkResponse]) error
	// GetChunk retrieves a chunk. The server streams the chunk data back
	// in fragments.
	GetChunk(*GetChunkRequest, grpc.ServerStreamingServer[GetChunkResponse]) error
	// DeleteChunk removes a chunk from the store.
	DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error)
	// HasChunk checks whether a chunk exists in the store.
	HasChunk(context.Context, *HasChunkRequest) (*HasChunkResponse, error)
	mustEmbedUnimplementedChunkServiceServer()
}

// UnimplementedChunkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkServiceServer struct{}

func (UnimplementedChunkServiceServer) PutChunk(grpc.ClientStreamingServer[PutChunkRequest, PutChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PutChunk not implemented")
}
func (UnimplementedChunkServiceServer) GetChunk(*GetChunkRequest, grpc.ServerStreamingServer[GetChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedChunkServiceServer) DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChunk not implemented")
}
func (UnimplementedChunkServiceServer) HasChunk(context.Context, *HasChunkRequest) (*HasChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasChunk not implemented")
}
func (UnimplementedChunkServiceServer) mustEmbedUnimplementedChunkServiceServer() {}
func (UnimplementedChunkServiceServer) testEmbeddedByValue()                      {}

// UnsafeChunkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkServiceServer will
// result in compilation errors.
type UnsafeChunkServiceServer interface {
	mustEmbedUnimplementedChunkServiceServer()
}

func RegisterChunkServiceServer(s grpc.ServiceRegistrar, srv ChunkServiceServer) {
	// If the following call pancis, it indicates UnimplementedChunkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkService_ServiceDesc, srv)
}

func _ChunkService_PutChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChunkServiceServer).PutChunk(&grpc.GenericServerStream[PutChunkRequest, PutChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkService_PutChunkServer = grpc.ClientStreamingServer[PutChunkRequest, PutChunkResponse]

func _ChunkService_GetChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChunkServiceServer).GetChunk(m, &grpc.GenericServerStream[GetChunkRequest, GetChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkService_GetChunkServer = grpc.ServerStreamingServer[GetChunkResponse]

func _ChunkService_DeleteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).DeleteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_DeleteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).DeleteChunk(ctx, req.(*DeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_HasChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).HasChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_HasChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).HasChunk(ctx, req.(*HasChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkService_ServiceDesc is the grpc.ServiceDesc for ChunkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chunk.ChunkService",
	HandlerType: (*ChunkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteChunk",
			Handler:    _ChunkService_DeleteChunk_Handler,
		},
		{
			MethodName: "HasChunk",
			Handler:    _ChunkService_HasChunk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutChunk",
			Handler:       _ChunkService_PutChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetChunk",
			Handler:       _ChunkService_GetChunk_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/chunk/chunk.proto",
}
