// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v6.33.4
// source: api/proto/nvme/nvme.proto

package nvme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTargetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// volume_id is the unique volume identifier, used to derive the NQN and
	// backing file name.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// size_bytes is the requested size for the backing sparse file.
	SizeBytes int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// ana_state is the initial ANA state for the target. Valid values are
	// "optimized" (active path) and "inaccessible" (passive path).
	// If empty, defaults to "optimized".
	AnaState string `protobuf:"bytes,3,opt,name=ana_state,json=anaState,proto3" json:"ana_state,omitempty"`
	// ana_group_id is the ANA group identifier for this target. All targets
	// sharing the same group ID transition state together during failover.
	AnaGroupId uint32 `protobuf:"varint,4,opt,name=ana_group_id,json=anaGroupId,proto3" json:"ana_group_id,omitempty"`
}

func (x *CreateTargetRequest) Reset() {
	*x = CreateTargetRequest{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTargetRequest) ProtoMessage() {}

func (x *CreateTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTargetRequest.ProtoReflect.Descriptor instead.
func (*CreateTargetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTargetRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *CreateTargetRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateTargetRequest) GetAnaState() string {
	if x != nil {
		return x.AnaState
	}
	return ""
}

func (x *CreateTargetRequest) GetAnaGroupId() uint32 {
	if x != nil {
		return x.AnaGroupId
	}
	return 0
}

type CreateTargetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// subsystem_nqn is the NVMe Qualified Name for the created subsystem,
	// e.g. "nqn.2024-01.io.novastor:vol-<uuid>".
	SubsystemNqn string `protobuf:"bytes,1,opt,name=subsystem_nqn,json=subsystemNqn,proto3" json:"subsystem_nqn,omitempty"`
	// target_address is the IP address the NVMe-oF port is bound to.
	TargetAddress string `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	// target_port is the TCP port the NVMe-oF target listens on (default "4420").
	TargetPort string `protobuf:"bytes,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
}

func (x *CreateTargetResponse) Reset() {
	*x = CreateTargetResponse{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTargetResponse) ProtoMessage() {}

func (x *CreateTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTargetResponse.ProtoReflect.Descriptor instead.
func (*CreateTargetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTargetResponse) GetSubsystemNqn() string {
	if x != nil {
		return x.SubsystemNqn
	}
	return ""
}

func (x *CreateTargetResponse) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *CreateTargetResponse) GetTargetPort() string {
	if x != nil {
		return x.TargetPort
	}
	return ""
}

type DeleteTargetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// volume_id identifies the target to tear down.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
}

func (x *DeleteTargetRequest) Reset() {
	*x = DeleteTargetRequest{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTargetRequest) ProtoMessage() {}

func (x *DeleteTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTargetRequest.ProtoReflect.Descriptor instead.
func (*DeleteTargetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTargetRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type DeleteTargetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTargetResponse) Reset() {
	*x = DeleteTargetResponse{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTargetResponse) ProtoMessage() {}

func (x *DeleteTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTargetResponse.ProtoReflect.Descriptor instead.
func (*DeleteTargetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{3}
}

type SetANAStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// volume_id identifies the NVMe-oF target whose ANA state should change.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// ana_state is the desired ANA state. Valid values are "optimized"
	// (active, accepting I/O) and "inaccessible" (passive, rejecting I/O).
	AnaState string `protobuf:"bytes,2,opt,name=ana_state,json=anaState,proto3" json:"ana_state,omitempty"`
	// ana_group_id is the ANA group to apply the state change to.
	AnaGroupId uint32 `protobuf:"varint,3,opt,name=ana_group_id,json=anaGroupId,proto3" json:"ana_group_id,omitempty"`
}

func (x *SetANAStateRequest) Reset() {
	*x = SetANAStateRequest{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetANAStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetANAStateRequest) ProtoMessage() {}

func (x *SetANAStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetANAStateRequest.ProtoReflect.Descriptor instead.
func (*SetANAStateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{4}
}

func (x *SetANAStateRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *SetANAStateRequest) GetAnaState() string {
	if x != nil {
		return x.AnaState
	}
	return ""
}

func (x *SetANAStateRequest) GetAnaGroupId() uint32 {
	if x != nil {
		return x.AnaGroupId
	}
	return 0
}

type SetANAStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetANAStateResponse) Reset() {
	*x = SetANAStateResponse{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetANAStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetANAStateResponse) ProtoMessage() {}

func (x *SetANAStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetANAStateResponse.ProtoReflect.Descriptor instead.
func (*SetANAStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{5}
}

// ReplicaTargetInfo describes a remote NVMe-oF target to replicate to.
type ReplicaTargetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// address is the IP address of the remote agent hosting the replica.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// port is the NVMe-oF TCP port (e.g. "4430").
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	// nqn is the NVMe Qualified Name of the remote subsystem.
	Nqn string `protobuf:"bytes,3,opt,name=nqn,proto3" json:"nqn,omitempty"`
}

func (x *ReplicaTargetInfo) Reset() {
	*x = ReplicaTargetInfo{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaTargetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaTargetInfo) ProtoMessage() {}

func (x *ReplicaTargetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaTargetInfo.ProtoReflect.Descriptor instead.
func (*ReplicaTargetInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicaTargetInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReplicaTargetInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ReplicaTargetInfo) GetNqn() string {
	if x != nil {
		return x.Nqn
	}
	return ""
}

type SetupReplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// volume_id identifies the volume to configure replication for.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// local_bdev_name is the SPDK bdev name for the local chunk volume
	// (e.g. "novastor_<volume_id>").
	LocalBdevName string `protobuf:"bytes,2,opt,name=local_bdev_name,json=localBdevName,proto3" json:"local_bdev_name,omitempty"`
	// remote_targets is the list of remote NVMe-oF targets to replicate to.
	RemoteTargets []*ReplicaTargetInfo `protobuf:"bytes,3,rep,name=remote_targets,json=remoteTargets,proto3" json:"remote_targets,omitempty"`
}

func (x *SetupReplicationRequest) Reset() {
	*x = SetupReplicationRequest{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupReplicationRequest) ProtoMessage() {}

func (x *SetupReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupReplicationRequest.ProtoReflect.Descriptor instead.
func (*SetupReplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{7}
}

func (x *SetupReplicationRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *SetupReplicationRequest) GetLocalBdevName() string {
	if x != nil {
		return x.LocalBdevName
	}
	return ""
}

func (x *SetupReplicationRequest) GetRemoteTargets() []*ReplicaTargetInfo {
	if x != nil {
		return x.RemoteTargets
	}
	return nil
}

type SetupReplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// replica_bdev_name is the name of the composite replica bdev.
	ReplicaBdevName string `protobuf:"bytes,1,opt,name=replica_bdev_name,json=replicaBdevName,proto3" json:"replica_bdev_name,omitempty"`
	// subsystem_nqn is the NQN of the re-exported NVMe-oF target.
	SubsystemNqn string `protobuf:"bytes,2,opt,name=subsystem_nqn,json=subsystemNqn,proto3" json:"subsystem_nqn,omitempty"`
}

func (x *SetupReplicationResponse) Reset() {
	*x = SetupReplicationResponse{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupReplicationResponse) ProtoMessage() {}

func (x *SetupReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupReplicationResponse.ProtoReflect.Descriptor instead.
func (*SetupReplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{8}
}

func (x *SetupReplicationResponse) GetReplicaBdevName() string {
	if x != nil {
		return x.ReplicaBdevName
	}
	return ""
}

func (x *SetupReplicationResponse) GetSubsystemNqn() string {
	if x != nil {
		return x.SubsystemNqn
	}
	return ""
}

var File_api_proto_nvme_nvme_proto protoreflect.FileDescriptor

var file_api_proto_nvme_nvme_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x76, 0x6d, 0x65,
	0x2f, 0x6e, 0x76, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x76, 0x6d,
	0x65, 0x22, 0x90, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6e, 0x61, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6e, 0x61, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x61, 0x6e, 0x61, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x6e, 0x61, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x75, 0x62, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x71, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e,
	0x71, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x32, 0x0a, 0x13, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x16,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x70, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x41, 0x4e, 0x41,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6e, 0x61,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6e,
	0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x61, 0x6e, 0x61, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x6e,
	0x61, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x41,
	0x4e, 0x41, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x53, 0x0a, 0x11, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x71, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6e, 0x71, 0x6e, 0x22, 0x9e, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x62, 0x64, 0x65, 0x76, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x42, 0x64, 0x65,
	0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x6e, 0x76, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0x6b, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x62, 0x64, 0x65,
	0x76, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x42, 0x64, 0x65, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x75, 0x62, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x71, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e,
	0x71, 0x6e, 0x32, 0xb8, 0x02, 0x0a, 0x11, 0x4e, 0x56, 0x4d, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x6e, 0x76, 0x6d, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x76, 0x6d, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x19, 0x2e, 0x6e, 0x76, 0x6d, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x76, 0x6d,
	0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x41, 0x4e, 0x41,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x6e, 0x76, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x74,
	0x41, 0x4e, 0x41, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x6e, 0x76, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x4e, 0x41, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d,
	0x2e, 0x6e, 0x76, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x6e, 0x76, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x7a, 0x72, 0x74,
	0x79, 0x64, 0x78, 0x62, 0x2f, 0x6e, 0x6f, 0x76, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x76, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_nvme_nvme_proto_rawDescOnce sync.Once
	file_api_proto_nvme_nvme_proto_rawDescData = file_api_proto_nvme_nvme_proto_rawDesc
)

func file_api_proto_nvme_nvme_proto_rawDescGZIP() []byte {
	file_api_proto_nvme_nvme_proto_rawDescOnce.Do(func() {
		file_api_proto_nvme_nvme_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_nvme_nvme_proto_rawDescData)
	})
	return file_api_proto_nvme_nvme_proto_rawDescData
}

var file_api_proto_nvme_nvme_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_nvme_nvme_proto_goTypes = []any{
	(*CreateTargetRequest)(nil),      // 0: nvme.CreateTargetRequest
	(*CreateTargetResponse)(nil),     // 1: nvme.CreateTargetResponse
	(*DeleteTargetRequest)(nil),      // 2: nvme.DeleteTargetRequest
	(*DeleteTargetResponse)(nil),     // 3: nvme.DeleteTargetResponse
	(*SetANAStateRequest)(nil),       // 4: nvme.SetANAStateRequest
	(*SetANAStateResponse)(nil),      // 5: nvme.SetANAStateResponse
	(*ReplicaTargetInfo)(nil),        // 6: nvme.ReplicaTargetInfo
	(*SetupReplicationRequest)(nil),  // 7: nvme.SetupReplicationRequest
	(*SetupReplicationResponse)(nil), // 8: nvme.SetupReplicationResponse
}
var file_api_proto_nvme_nvme_proto_depIdxs = []int32{
	6, // 0: nvme.SetupReplicationRequest.remote_targets:type_name -> nvme.ReplicaTargetInfo
	0, // 1: nvme.NVMeTargetService.CreateTarget:input_type -> nvme.CreateTargetRequest
	2, // 2: nvme.NVMeTargetService.DeleteTarget:input_type -> nvme.DeleteTargetRequest
	4, // 3: nvme.NVMeTargetService.SetANAState:input_type -> nvme.SetANAStateRequest
	7, // 4: nvme.NVMeTargetService.SetupReplication:input_type -> nvme.SetupReplicationRequest
	1, // 5: nvme.NVMeTargetService.CreateTarget:output_type -> nvme.CreateTargetResponse
	3, // 6: nvme.NVMeTargetService.DeleteTarget:output_type -> nvme.DeleteTargetResponse
	5, // 7: nvme.NVMeTargetService.SetANAState:output_type -> nvme.SetANAStateResponse
	8, // 8: nvme.NVMeTargetService.SetupReplication:output_type -> nvme.SetupReplicationResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_nvme_nvme_proto_init() }
func file_api_proto_nvme_nvme_proto_init() {
	if File_api_proto_nvme_nvme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_nvme_nvme_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_nvme_nvme_proto_goTypes,
		DependencyIndexes: file_api_proto_nvme_nvme_proto_depIdxs,
		MessageInfos:      file_api_proto_nvme_nvme_proto_msgTypes,
	}.Build()
	File_api_proto_nvme_nvme_proto = out.File
	file_api_proto_nvme_nvme_proto_rawDesc = nil
	file_api_proto_nvme_nvme_proto_goTypes = nil
	file_api_proto_nvme_nvme_proto_depIdxs = nil
}
