// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: api/proto/nvme/nvme.proto

package nvme

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NVMeTargetService_CreateTarget_FullMethodName = "/nvme.NVMeTargetService/CreateTarget"
	NVMeTargetService_DeleteTarget_FullMethodName = "/nvme.NVMeTargetService/DeleteTarget"
	NVMeTargetService_SetANAState_FullMethodName  = "/nvme.NVMeTargetService/SetANAState"
	NVMeTargetService_ListTargets_FullMethodName  = "/nvme.NVMeTargetService/ListTargets"
)

// NVMeTargetServiceClient is the client API for NVMeTargetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NVMeTargetService manages NVMe-oF/TCP targets on storage agent nodes.
// The CSI controller calls this service during CreateVolume/DeleteVolume
// to create and tear down backing block devices exposed via nvmet configfs.
//
// Replication and erasure coding are handled by the Rust dataplane's chunk
// engine — the presentation layer (NVMe-oF) is thin protocol translation only.
type NVMeTargetServiceClient interface {
	// CreateTarget creates a chunk-backed volume and exposes it as an
	// NVMe-oF/TCP target via the data-plane. The volume's protection scheme
	// (replication or EC) is configured in the chunk engine at creation time.
	CreateTarget(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*CreateTargetResponse, error)
	// DeleteTarget removes the NVMe-oF target, detaches the loop device,
	// and deletes the sparse backing file.
	DeleteTarget(ctx context.Context, in *DeleteTargetRequest, opts ...grpc.CallOption) (*DeleteTargetResponse, error)
	// SetANAState changes the ANA (Asymmetric Namespace Access) state for a
	// volume's NVMe-oF target. Used during active-passive failover to transition
	// a target between optimized (active) and inaccessible (passive) states.
	SetANAState(ctx context.Context, in *SetANAStateRequest, opts ...grpc.CallOption) (*SetANAStateResponse, error)
	// ListTargets returns all currently active NVMe-oF targets on this node.
	// Used by the reconciliation loop to compare desired vs actual state.
	ListTargets(ctx context.Context, in *ListTargetsRequest, opts ...grpc.CallOption) (*ListTargetsResponse, error)
}

type nVMeTargetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNVMeTargetServiceClient(cc grpc.ClientConnInterface) NVMeTargetServiceClient {
	return &nVMeTargetServiceClient{cc}
}

func (c *nVMeTargetServiceClient) CreateTarget(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*CreateTargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTargetResponse)
	err := c.cc.Invoke(ctx, NVMeTargetService_CreateTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nVMeTargetServiceClient) DeleteTarget(ctx context.Context, in *DeleteTargetRequest, opts ...grpc.CallOption) (*DeleteTargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTargetResponse)
	err := c.cc.Invoke(ctx, NVMeTargetService_DeleteTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nVMeTargetServiceClient) SetANAState(ctx context.Context, in *SetANAStateRequest, opts ...grpc.CallOption) (*SetANAStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetANAStateResponse)
	err := c.cc.Invoke(ctx, NVMeTargetService_SetANAState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nVMeTargetServiceClient) ListTargets(ctx context.Context, in *ListTargetsRequest, opts ...grpc.CallOption) (*ListTargetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTargetsResponse)
	err := c.cc.Invoke(ctx, NVMeTargetService_ListTargets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NVMeTargetServiceServer is the server API for NVMeTargetService service.
// All implementations must embed UnimplementedNVMeTargetServiceServer
// for forward compatibility.
//
// NVMeTargetService manages NVMe-oF/TCP targets on storage agent nodes.
// The CSI controller calls this service during CreateVolume/DeleteVolume
// to create and tear down backing block devices exposed via nvmet configfs.
//
// Replication and erasure coding are handled by the Rust dataplane's chunk
// engine — the presentation layer (NVMe-oF) is thin protocol translation only.
type NVMeTargetServiceServer interface {
	// CreateTarget creates a chunk-backed volume and exposes it as an
	// NVMe-oF/TCP target via the data-plane. The volume's protection scheme
	// (replication or EC) is configured in the chunk engine at creation time.
	CreateTarget(context.Context, *CreateTargetRequest) (*CreateTargetResponse, error)
	// DeleteTarget removes the NVMe-oF target, detaches the loop device,
	// and deletes the sparse backing file.
	DeleteTarget(context.Context, *DeleteTargetRequest) (*DeleteTargetResponse, error)
	// SetANAState changes the ANA (Asymmetric Namespace Access) state for a
	// volume's NVMe-oF target. Used during active-passive failover to transition
	// a target between optimized (active) and inaccessible (passive) states.
	SetANAState(context.Context, *SetANAStateRequest) (*SetANAStateResponse, error)
	// ListTargets returns all currently active NVMe-oF targets on this node.
	// Used by the reconciliation loop to compare desired vs actual state.
	ListTargets(context.Context, *ListTargetsRequest) (*ListTargetsResponse, error)
	mustEmbedUnimplementedNVMeTargetServiceServer()
}

// UnimplementedNVMeTargetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNVMeTargetServiceServer struct{}

func (UnimplementedNVMeTargetServiceServer) CreateTarget(context.Context, *CreateTargetRequest) (*CreateTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTarget not implemented")
}
func (UnimplementedNVMeTargetServiceServer) DeleteTarget(context.Context, *DeleteTargetRequest) (*DeleteTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTarget not implemented")
}
func (UnimplementedNVMeTargetServiceServer) SetANAState(context.Context, *SetANAStateRequest) (*SetANAStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetANAState not implemented")
}
func (UnimplementedNVMeTargetServiceServer) ListTargets(context.Context, *ListTargetsRequest) (*ListTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTargets not implemented")
}
func (UnimplementedNVMeTargetServiceServer) mustEmbedUnimplementedNVMeTargetServiceServer() {}
func (UnimplementedNVMeTargetServiceServer) testEmbeddedByValue()                           {}

// UnsafeNVMeTargetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NVMeTargetServiceServer will
// result in compilation errors.
type UnsafeNVMeTargetServiceServer interface {
	mustEmbedUnimplementedNVMeTargetServiceServer()
}

func RegisterNVMeTargetServiceServer(s grpc.ServiceRegistrar, srv NVMeTargetServiceServer) {
	// If the following call pancis, it indicates UnimplementedNVMeTargetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NVMeTargetService_ServiceDesc, srv)
}

func _NVMeTargetService_CreateTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMeTargetServiceServer).CreateTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NVMeTargetService_CreateTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMeTargetServiceServer).CreateTarget(ctx, req.(*CreateTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NVMeTargetService_DeleteTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMeTargetServiceServer).DeleteTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NVMeTargetService_DeleteTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMeTargetServiceServer).DeleteTarget(ctx, req.(*DeleteTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NVMeTargetService_SetANAState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetANAStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMeTargetServiceServer).SetANAState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NVMeTargetService_SetANAState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMeTargetServiceServer).SetANAState(ctx, req.(*SetANAStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NVMeTargetService_ListTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVMeTargetServiceServer).ListTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NVMeTargetService_ListTargets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVMeTargetServiceServer).ListTargets(ctx, req.(*ListTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NVMeTargetService_ServiceDesc is the grpc.ServiceDesc for NVMeTargetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NVMeTargetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvme.NVMeTargetService",
	HandlerType: (*NVMeTargetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTarget",
			Handler:    _NVMeTargetService_CreateTarget_Handler,
		},
		{
			MethodName: "DeleteTarget",
			Handler:    _NVMeTargetService_DeleteTarget_Handler,
		},
		{
			MethodName: "SetANAState",
			Handler:    _NVMeTargetService_SetANAState_Handler,
		},
		{
			MethodName: "ListTargets",
			Handler:    _NVMeTargetService_ListTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/nvme/nvme.proto",
}
