// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/nvme/nvme.proto

package nvme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTargetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_id is the unique volume identifier, used to derive the NQN and
	// backing file name.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// size_bytes is the requested size for the backing sparse file.
	SizeBytes     int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTargetRequest) Reset() {
	*x = CreateTargetRequest{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTargetRequest) ProtoMessage() {}

func (x *CreateTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTargetRequest.ProtoReflect.Descriptor instead.
func (*CreateTargetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTargetRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *CreateTargetRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type CreateTargetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subsystem_nqn is the NVMe Qualified Name for the created subsystem,
	// e.g. "nqn.2024-01.io.novastor:vol-<uuid>".
	SubsystemNqn string `protobuf:"bytes,1,opt,name=subsystem_nqn,json=subsystemNqn,proto3" json:"subsystem_nqn,omitempty"`
	// target_address is the IP address the NVMe-oF port is bound to.
	TargetAddress string `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	// target_port is the TCP port the NVMe-oF target listens on (default "4420").
	TargetPort    string `protobuf:"bytes,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTargetResponse) Reset() {
	*x = CreateTargetResponse{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTargetResponse) ProtoMessage() {}

func (x *CreateTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTargetResponse.ProtoReflect.Descriptor instead.
func (*CreateTargetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTargetResponse) GetSubsystemNqn() string {
	if x != nil {
		return x.SubsystemNqn
	}
	return ""
}

func (x *CreateTargetResponse) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *CreateTargetResponse) GetTargetPort() string {
	if x != nil {
		return x.TargetPort
	}
	return ""
}

type DeleteTargetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_id identifies the target to tear down.
	VolumeId      string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTargetRequest) Reset() {
	*x = DeleteTargetRequest{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTargetRequest) ProtoMessage() {}

func (x *DeleteTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTargetRequest.ProtoReflect.Descriptor instead.
func (*DeleteTargetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTargetRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type DeleteTargetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTargetResponse) Reset() {
	*x = DeleteTargetResponse{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTargetResponse) ProtoMessage() {}

func (x *DeleteTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTargetResponse.ProtoReflect.Descriptor instead.
func (*DeleteTargetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{3}
}

var File_api_proto_nvme_nvme_proto protoreflect.FileDescriptor

const file_api_proto_nvme_nvme_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/nvme/nvme.proto\x12\x04nvme\"Q\n" +
	"\x13CreateTargetRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\"\x83\x01\n" +
	"\x14CreateTargetResponse\x12#\n" +
	"\rsubsystem_nqn\x18\x01 \x01(\tR\fsubsystemNqn\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\tR\rtargetAddress\x12\x1f\n" +
	"\vtarget_port\x18\x03 \x01(\tR\n" +
	"targetPort\"2\n" +
	"\x13DeleteTargetRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"\x16\n" +
	"\x14DeleteTargetResponse2\xa1\x01\n" +
	"\x11NVMeTargetService\x12E\n" +
	"\fCreateTarget\x12\x19.nvme.CreateTargetRequest\x1a\x1a.nvme.CreateTargetResponse\x12E\n" +
	"\fDeleteTarget\x12\x19.nvme.DeleteTargetRequest\x1a\x1a.nvme.DeleteTargetResponseB-Z+github.com/piwi3910/novastor/api/proto/nvmeb\x06proto3"

var (
	file_api_proto_nvme_nvme_proto_rawDescOnce sync.Once
	file_api_proto_nvme_nvme_proto_rawDescData []byte
)

func file_api_proto_nvme_nvme_proto_rawDescGZIP() []byte {
	file_api_proto_nvme_nvme_proto_rawDescOnce.Do(func() {
		file_api_proto_nvme_nvme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_nvme_nvme_proto_rawDesc), len(file_api_proto_nvme_nvme_proto_rawDesc)))
	})
	return file_api_proto_nvme_nvme_proto_rawDescData
}

var file_api_proto_nvme_nvme_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_nvme_nvme_proto_goTypes = []any{
	(*CreateTargetRequest)(nil),  // 0: nvme.CreateTargetRequest
	(*CreateTargetResponse)(nil), // 1: nvme.CreateTargetResponse
	(*DeleteTargetRequest)(nil),  // 2: nvme.DeleteTargetRequest
	(*DeleteTargetResponse)(nil), // 3: nvme.DeleteTargetResponse
}
var file_api_proto_nvme_nvme_proto_depIdxs = []int32{
	0, // 0: nvme.NVMeTargetService.CreateTarget:input_type -> nvme.CreateTargetRequest
	2, // 1: nvme.NVMeTargetService.DeleteTarget:input_type -> nvme.DeleteTargetRequest
	1, // 2: nvme.NVMeTargetService.CreateTarget:output_type -> nvme.CreateTargetResponse
	3, // 3: nvme.NVMeTargetService.DeleteTarget:output_type -> nvme.DeleteTargetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_nvme_nvme_proto_init() }
func file_api_proto_nvme_nvme_proto_init() {
	if File_api_proto_nvme_nvme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_nvme_nvme_proto_rawDesc), len(file_api_proto_nvme_nvme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_nvme_nvme_proto_goTypes,
		DependencyIndexes: file_api_proto_nvme_nvme_proto_depIdxs,
		MessageInfos:      file_api_proto_nvme_nvme_proto_msgTypes,
	}.Build()
	File_api_proto_nvme_nvme_proto = out.File
	file_api_proto_nvme_nvme_proto_goTypes = nil
	file_api_proto_nvme_nvme_proto_depIdxs = nil
}
