// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/nvme/nvme.proto

package nvme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTargetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_id is the unique volume identifier, used to derive the NQN and
	// backing file name.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// size_bytes is the requested size for the backing sparse file.
	SizeBytes int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// ana_state is the initial ANA state for the target. Valid values are
	// "optimized" (active path) and "inaccessible" (passive path).
	// If empty, defaults to "optimized".
	AnaState string `protobuf:"bytes,3,opt,name=ana_state,json=anaState,proto3" json:"ana_state,omitempty"`
	// ana_group_id is the ANA group identifier for this target. All targets
	// sharing the same group ID transition state together during failover.
	AnaGroupId uint32 `protobuf:"varint,4,opt,name=ana_group_id,json=anaGroupId,proto3" json:"ana_group_id,omitempty"`
	// protection configures the data protection scheme for this volume.
	// If not set, defaults to replication with factor 1.
	Protection    *VolumeProtection `protobuf:"bytes,5,opt,name=protection,proto3" json:"protection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTargetRequest) Reset() {
	*x = CreateTargetRequest{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTargetRequest) ProtoMessage() {}

func (x *CreateTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTargetRequest.ProtoReflect.Descriptor instead.
func (*CreateTargetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTargetRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *CreateTargetRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateTargetRequest) GetAnaState() string {
	if x != nil {
		return x.AnaState
	}
	return ""
}

func (x *CreateTargetRequest) GetAnaGroupId() uint32 {
	if x != nil {
		return x.AnaGroupId
	}
	return 0
}

func (x *CreateTargetRequest) GetProtection() *VolumeProtection {
	if x != nil {
		return x.Protection
	}
	return nil
}

// VolumeProtection describes the data protection scheme for a volume.
// Replication and erasure coding are handled by the chunk engine in the
// Rust dataplane — the presentation layer does not participate in replication.
type VolumeProtection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "replication" or "erasure_coding"
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// For replication: number of copies (e.g. 3).
	ReplicationFactor uint32 `protobuf:"varint,2,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	// For erasure coding: number of data shards (e.g. 4).
	DataShards uint32 `protobuf:"varint,3,opt,name=data_shards,json=dataShards,proto3" json:"data_shards,omitempty"`
	// For erasure coding: number of parity shards (e.g. 2).
	ParityShards  uint32 `protobuf:"varint,4,opt,name=parity_shards,json=parityShards,proto3" json:"parity_shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeProtection) Reset() {
	*x = VolumeProtection{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeProtection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeProtection) ProtoMessage() {}

func (x *VolumeProtection) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeProtection.ProtoReflect.Descriptor instead.
func (*VolumeProtection) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{1}
}

func (x *VolumeProtection) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *VolumeProtection) GetReplicationFactor() uint32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *VolumeProtection) GetDataShards() uint32 {
	if x != nil {
		return x.DataShards
	}
	return 0
}

func (x *VolumeProtection) GetParityShards() uint32 {
	if x != nil {
		return x.ParityShards
	}
	return 0
}

type CreateTargetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subsystem_nqn is the NVMe Qualified Name for the created subsystem,
	// e.g. "nqn.2024-01.io.novastor:vol-<uuid>".
	SubsystemNqn string `protobuf:"bytes,1,opt,name=subsystem_nqn,json=subsystemNqn,proto3" json:"subsystem_nqn,omitempty"`
	// target_address is the IP address the NVMe-oF port is bound to.
	TargetAddress string `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	// target_port is the TCP port the NVMe-oF target listens on (default "4420").
	TargetPort    string `protobuf:"bytes,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTargetResponse) Reset() {
	*x = CreateTargetResponse{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTargetResponse) ProtoMessage() {}

func (x *CreateTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTargetResponse.ProtoReflect.Descriptor instead.
func (*CreateTargetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTargetResponse) GetSubsystemNqn() string {
	if x != nil {
		return x.SubsystemNqn
	}
	return ""
}

func (x *CreateTargetResponse) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *CreateTargetResponse) GetTargetPort() string {
	if x != nil {
		return x.TargetPort
	}
	return ""
}

type DeleteTargetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_id identifies the target to tear down.
	VolumeId      string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTargetRequest) Reset() {
	*x = DeleteTargetRequest{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTargetRequest) ProtoMessage() {}

func (x *DeleteTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTargetRequest.ProtoReflect.Descriptor instead.
func (*DeleteTargetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTargetRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type DeleteTargetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTargetResponse) Reset() {
	*x = DeleteTargetResponse{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTargetResponse) ProtoMessage() {}

func (x *DeleteTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTargetResponse.ProtoReflect.Descriptor instead.
func (*DeleteTargetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{4}
}

type SetANAStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_id identifies the NVMe-oF target whose ANA state should change.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// ana_state is the desired ANA state. Valid values are "optimized"
	// (active, accepting I/O) and "inaccessible" (passive, rejecting I/O).
	AnaState string `protobuf:"bytes,2,opt,name=ana_state,json=anaState,proto3" json:"ana_state,omitempty"`
	// ana_group_id is the ANA group to apply the state change to.
	AnaGroupId    uint32 `protobuf:"varint,3,opt,name=ana_group_id,json=anaGroupId,proto3" json:"ana_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetANAStateRequest) Reset() {
	*x = SetANAStateRequest{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetANAStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetANAStateRequest) ProtoMessage() {}

func (x *SetANAStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetANAStateRequest.ProtoReflect.Descriptor instead.
func (*SetANAStateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{5}
}

func (x *SetANAStateRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *SetANAStateRequest) GetAnaState() string {
	if x != nil {
		return x.AnaState
	}
	return ""
}

func (x *SetANAStateRequest) GetAnaGroupId() uint32 {
	if x != nil {
		return x.AnaGroupId
	}
	return 0
}

type SetANAStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetANAStateResponse) Reset() {
	*x = SetANAStateResponse{}
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetANAStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetANAStateResponse) ProtoMessage() {}

func (x *SetANAStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nvme_nvme_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetANAStateResponse.ProtoReflect.Descriptor instead.
func (*SetANAStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nvme_nvme_proto_rawDescGZIP(), []int{6}
}

var File_api_proto_nvme_nvme_proto protoreflect.FileDescriptor

const file_api_proto_nvme_nvme_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/nvme/nvme.proto\x12\x04nvme\"\xc8\x01\n" +
	"\x13CreateTargetRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tana_state\x18\x03 \x01(\tR\banaState\x12 \n" +
	"\fana_group_id\x18\x04 \x01(\rR\n" +
	"anaGroupId\x126\n" +
	"\n" +
	"protection\x18\x05 \x01(\v2\x16.nvme.VolumeProtectionR\n" +
	"protection\"\x9b\x01\n" +
	"\x10VolumeProtection\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12-\n" +
	"\x12replication_factor\x18\x02 \x01(\rR\x11replicationFactor\x12\x1f\n" +
	"\vdata_shards\x18\x03 \x01(\rR\n" +
	"dataShards\x12#\n" +
	"\rparity_shards\x18\x04 \x01(\rR\fparityShards\"\x83\x01\n" +
	"\x14CreateTargetResponse\x12#\n" +
	"\rsubsystem_nqn\x18\x01 \x01(\tR\fsubsystemNqn\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\tR\rtargetAddress\x12\x1f\n" +
	"\vtarget_port\x18\x03 \x01(\tR\n" +
	"targetPort\"2\n" +
	"\x13DeleteTargetRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"\x16\n" +
	"\x14DeleteTargetResponse\"p\n" +
	"\x12SetANAStateRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1b\n" +
	"\tana_state\x18\x02 \x01(\tR\banaState\x12 \n" +
	"\fana_group_id\x18\x03 \x01(\rR\n" +
	"anaGroupId\"\x15\n" +
	"\x13SetANAStateResponse2\xe5\x01\n" +
	"\x11NVMeTargetService\x12E\n" +
	"\fCreateTarget\x12\x19.nvme.CreateTargetRequest\x1a\x1a.nvme.CreateTargetResponse\x12E\n" +
	"\fDeleteTarget\x12\x19.nvme.DeleteTargetRequest\x1a\x1a.nvme.DeleteTargetResponse\x12B\n" +
	"\vSetANAState\x12\x18.nvme.SetANAStateRequest\x1a\x19.nvme.SetANAStateResponseB-Z+github.com/azrtydxb/novastor/api/proto/nvmeb\x06proto3"

var (
	file_api_proto_nvme_nvme_proto_rawDescOnce sync.Once
	file_api_proto_nvme_nvme_proto_rawDescData []byte
)

func file_api_proto_nvme_nvme_proto_rawDescGZIP() []byte {
	file_api_proto_nvme_nvme_proto_rawDescOnce.Do(func() {
		file_api_proto_nvme_nvme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_nvme_nvme_proto_rawDesc), len(file_api_proto_nvme_nvme_proto_rawDesc)))
	})
	return file_api_proto_nvme_nvme_proto_rawDescData
}

var file_api_proto_nvme_nvme_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_nvme_nvme_proto_goTypes = []any{
	(*CreateTargetRequest)(nil),  // 0: nvme.CreateTargetRequest
	(*VolumeProtection)(nil),     // 1: nvme.VolumeProtection
	(*CreateTargetResponse)(nil), // 2: nvme.CreateTargetResponse
	(*DeleteTargetRequest)(nil),  // 3: nvme.DeleteTargetRequest
	(*DeleteTargetResponse)(nil), // 4: nvme.DeleteTargetResponse
	(*SetANAStateRequest)(nil),   // 5: nvme.SetANAStateRequest
	(*SetANAStateResponse)(nil),  // 6: nvme.SetANAStateResponse
}
var file_api_proto_nvme_nvme_proto_depIdxs = []int32{
	1, // 0: nvme.CreateTargetRequest.protection:type_name -> nvme.VolumeProtection
	0, // 1: nvme.NVMeTargetService.CreateTarget:input_type -> nvme.CreateTargetRequest
	3, // 2: nvme.NVMeTargetService.DeleteTarget:input_type -> nvme.DeleteTargetRequest
	5, // 3: nvme.NVMeTargetService.SetANAState:input_type -> nvme.SetANAStateRequest
	2, // 4: nvme.NVMeTargetService.CreateTarget:output_type -> nvme.CreateTargetResponse
	4, // 5: nvme.NVMeTargetService.DeleteTarget:output_type -> nvme.DeleteTargetResponse
	6, // 6: nvme.NVMeTargetService.SetANAState:output_type -> nvme.SetANAStateResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_nvme_nvme_proto_init() }
func file_api_proto_nvme_nvme_proto_init() {
	if File_api_proto_nvme_nvme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_nvme_nvme_proto_rawDesc), len(file_api_proto_nvme_nvme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_nvme_nvme_proto_goTypes,
		DependencyIndexes: file_api_proto_nvme_nvme_proto_depIdxs,
		MessageInfos:      file_api_proto_nvme_nvme_proto_msgTypes,
	}.Build()
	File_api_proto_nvme_nvme_proto = out.File
	file_api_proto_nvme_nvme_proto_goTypes = nil
	file_api_proto_nvme_nvme_proto_depIdxs = nil
}
