package agent

import (
	"context"
	"fmt"
	"strings"
	"sync"

	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	pb "github.com/azrtydxb/novastor/api/proto/nvme"
	"github.com/azrtydxb/novastor/internal/logging"
	"github.com/azrtydxb/novastor/internal/metadata"
	"github.com/azrtydxb/novastor/internal/spdk"
)

const (
	// spdkTargetPort is the TCP port used by SPDK NVMe-oF targets on this node.
	spdkTargetPort = 4430

	// spdkNQNPrefix matches the NQN format generated by the Rust data-plane.
	spdkNQNPrefix = "nqn.2024-01.io.novastor:volume-"
)

// SPDKTargetServer implements the NVMeTargetService gRPC server using the SPDK
// data-plane process. Volumes are created as lvols on the SPDK data-plane and
// exposed as NVMe-oF/TCP targets. All data-path I/O is handled by the Rust
// SPDK data-plane process; the Go agent never touches data.
type SPDKTargetServer struct {
	pb.UnimplementedNVMeTargetServiceServer

	hostIP     string
	baseBdev   string
	spdkClient *spdk.Client
	metaClient *metadata.GRPCClient

	// lvsInit tracks whether the lvol store has been initialised.
	initOnce sync.Once
	initErr  error
	// lvsName is the auto-generated lvol store name returned by the data-plane.
	lvsName string
}

// NewSPDKTargetServer creates an SPDKTargetServer that exposes NVMe-oF targets
// through the SPDK data-plane process reachable via the provided spdkClient.
// baseBdev is the name of the SPDK bdev to use as the backing device for the
// lvol store (e.g. "NVMe0n1" for real NVMe drives, "Malloc0" for testing).
func NewSPDKTargetServer(hostIP, baseBdev string, spdkClient *spdk.Client, metaClient *metadata.GRPCClient) *SPDKTargetServer {
	logging.L.Info("spdk target: initialized SPDK target server",
		zap.String("hostIP", hostIP),
		zap.String("baseBdev", baseBdev),
	)
	return &SPDKTargetServer{
		hostIP:     hostIP,
		baseBdev:   baseBdev,
		spdkClient: spdkClient,
		metaClient: metaClient,
	}
}

// Register adds the NVMeTargetService to the given gRPC server.
func (s *SPDKTargetServer) Register(srv *grpc.Server) {
	pb.RegisterNVMeTargetServiceServer(srv, s)
}

// mallocBdevSizeMB is the size of the auto-created Malloc bdev (256MB).
// Must fit within the SPDK memory allocation (1024MB) minus SPDK/DPDK overhead (~700MB).
const mallocBdevSizeMB = 256

// ensureLvolStore initialises the lvol store on first use. The underlying
// bdev is determined by the data-plane configuration (typically NVMe0n1 or
// Malloc0 for testing). This is called lazily so the agent can start even
// if the storage bdev isn't immediately available.
//
// All operations use SPDK's built-in RPC (native socket) for reliable
// error handling and to ensure the reactor thread processes each operation
// synchronously.
func (s *SPDKTargetServer) ensureLvolStore() error {
	s.initOnce.Do(func() {
		lvsName := fmt.Sprintf("lvs_%s", s.baseBdev)

		// Check if the lvol store already exists (dataplane survives agent restarts).
		stores, err := s.spdkClient.NativeGetLvolStores(lvsName)
		if err == nil && len(stores) > 0 {
			s.lvsName = stores[0].Name
			logging.L.Info("spdk target: lvol store already exists, reusing",
				zap.String("lvsName", s.lvsName),
			)
			return
		}

		// Auto-create a Malloc bdev when configured for testing (no real NVMe).
		if strings.HasPrefix(s.baseBdev, "Malloc") {
			logging.L.Info("spdk target: creating malloc bdev for testing",
				zap.String("name", s.baseBdev),
				zap.Uint64("sizeMB", mallocBdevSizeMB),
			)
			if err := s.spdkClient.NativeCreateMallocBdev(s.baseBdev, mallocBdevSizeMB, 512); err != nil {
				// EEXIST — the bdev persists across agent restarts.
				if !strings.Contains(err.Error(), "already exists") {
					s.initErr = fmt.Errorf("creating malloc bdev %s: %w", s.baseBdev, err)
					logging.L.Error("spdk target: failed to create malloc bdev", zap.Error(s.initErr))
					return
				}
				logging.L.Info("spdk target: malloc bdev already exists, reusing",
					zap.String("name", s.baseBdev),
				)
			}
		}

		uuid, err := s.spdkClient.NativeCreateLvolStore(s.baseBdev, lvsName)
		if err != nil {
			s.initErr = fmt.Errorf("creating lvol store on %s: %w", s.baseBdev, err)
			logging.L.Error("spdk target: failed to create lvol store", zap.Error(s.initErr))
			return
		}
		s.lvsName = lvsName
		logging.L.Info("spdk target: lvol store initialised",
			zap.String("lvsName", lvsName),
			zap.String("uuid", uuid),
		)
	})
	return s.initErr
}

// CreateTarget creates an lvol volume and exposes it as an NVMe-oF/TCP
// target via the data-plane process.
func (s *SPDKTargetServer) CreateTarget(ctx context.Context, req *pb.CreateTargetRequest) (*pb.CreateTargetResponse, error) {
	volumeID := req.GetVolumeId()
	if volumeID == "" {
		return nil, status.Error(codes.InvalidArgument, "volume_id is required")
	}
	sizeBytes := req.GetSizeBytes()
	if sizeBytes <= 0 {
		return nil, status.Error(codes.InvalidArgument, "size_bytes must be positive")
	}

	// Ensure lvol store is ready.
	if err := s.ensureLvolStore(); err != nil {
		return nil, status.Errorf(codes.Internal, "lvol store init: %v", err)
	}

	// Create lvol via SPDK native RPC.
	bdevName, err := s.spdkClient.NativeCreateLvol(s.lvsName, volumeID, uint64(sizeBytes))
	if err != nil {
		logging.L.Error("spdk target: failed to create lvol",
			zap.String("volumeID", volumeID),
			zap.Int64("sizeBytes", sizeBytes),
			zap.Error(err),
		)
		return nil, status.Errorf(codes.Internal, "creating lvol for %s: %v", volumeID, err)
	}

	logging.L.Info("spdk target: lvol created",
		zap.String("volumeID", volumeID),
		zap.String("bdevName", bdevName),
		zap.Int64("sizeBytes", sizeBytes),
	)

	// Expose the lvol bdev as an NVMe-oF/TCP target.
	// Use the specific host IP (not 0.0.0.0) because SPDK's listener ACL
	// performs a literal address comparison: the subsystem listener address
	// must match the address the client connects to.
	nqn, err := s.spdkClient.CreateNvmfTarget(volumeID, s.hostIP, spdkTargetPort, bdevName)
	if err != nil {
		// Cleanup lvol on failure.
		if delErr := s.spdkClient.NativeDeleteBdev(bdevName); delErr != nil {
			logging.L.Warn("spdk target: failed to clean up lvol",
				zap.String("volumeID", volumeID),
				zap.Error(delErr),
			)
		}
		logging.L.Error("spdk target: failed to create NVMe-oF target",
			zap.String("volumeID", volumeID),
			zap.Error(err),
		)
		return nil, status.Errorf(codes.Internal, "creating NVMe-oF target for %s: %v", volumeID, err)
	}

	logging.L.Info("spdk target: target created",
		zap.String("volumeID", volumeID),
		zap.String("nqn", nqn),
		zap.String("address", s.hostIP),
		zap.Int("port", spdkTargetPort),
		zap.String("bdevName", bdevName),
	)

	// Set ANA state if specified.
	anaState := req.GetAnaState()
	anaGroupID := req.GetAnaGroupId()
	if anaState != "" && anaGroupID > 0 {
		if err := s.spdkClient.SetANAState(nqn, anaGroupID, anaState); err != nil {
			logging.L.Warn("spdk target: failed to set ANA state",
				zap.String("volumeID", volumeID),
				zap.String("anaState", anaState),
				zap.Uint32("anaGroupID", anaGroupID),
				zap.Error(err),
			)
			// Non-fatal: target works without ANA.
		} else {
			logging.L.Info("spdk target: ANA state set",
				zap.String("volumeID", volumeID),
				zap.String("anaState", anaState),
				zap.Uint32("anaGroupID", anaGroupID),
			)
		}
	}

	return &pb.CreateTargetResponse{
		SubsystemNqn:  nqn,
		TargetAddress: s.hostIP,
		TargetPort:    fmt.Sprintf("%d", spdkTargetPort),
	}, nil
}

// DeleteTarget removes the NVMe-oF target and the lvol via the data-plane.
func (s *SPDKTargetServer) DeleteTarget(ctx context.Context, req *pb.DeleteTargetRequest) (*pb.DeleteTargetResponse, error) {
	volumeID := req.GetVolumeId()
	if volumeID == "" {
		return nil, status.Error(codes.InvalidArgument, "volume_id is required")
	}

	bdevName := fmt.Sprintf("%s/%s", s.lvsName, volumeID)

	// Remove the NVMe-oF target (best-effort; target may not exist on retry).
	if err := s.spdkClient.DeleteNvmfTarget(volumeID); err != nil {
		logging.L.Warn("spdk target: failed to delete NVMe-oF target",
			zap.String("volumeID", volumeID),
			zap.Error(err),
		)
	}

	// Remove the lvol bdev via native RPC (best-effort).
	if err := s.spdkClient.NativeDeleteBdev(bdevName); err != nil {
		logging.L.Warn("spdk target: failed to delete lvol bdev",
			zap.String("volumeID", volumeID),
			zap.String("bdevName", bdevName),
			zap.Error(err),
		)
	}

	logging.L.Info("spdk target: target deleted", zap.String("volumeID", volumeID))
	return &pb.DeleteTargetResponse{}, nil
}

// SetANAState changes the ANA state for a volume's NVMe-oF target subsystem.
func (s *SPDKTargetServer) SetANAState(ctx context.Context, req *pb.SetANAStateRequest) (*pb.SetANAStateResponse, error) {
	volumeID := req.GetVolumeId()
	if volumeID == "" {
		return nil, status.Error(codes.InvalidArgument, "volume_id required")
	}

	nqn := spdkNQNPrefix + volumeID
	if err := s.spdkClient.SetANAState(nqn, req.GetAnaGroupId(), req.GetAnaState()); err != nil {
		return nil, status.Errorf(codes.Internal, "set ANA state for %s: %v", volumeID, err)
	}

	logging.L.Info("spdk target: ANA state updated",
		zap.String("volumeID", volumeID),
		zap.String("anaState", req.GetAnaState()),
		zap.Uint32("anaGroupID", req.GetAnaGroupId()),
	)

	return &pb.SetANAStateResponse{}, nil
}
