apiVersion: novastor.io/v1alpha1
kind: SharedFilesystem
metadata:
  name: ml-datasets
spec:
  pool: ssd-erasurecoded
  capacity: "1Ti"
  accessMode: ReadWriteMany
  dataProtection:
    mode: replication
    replication:
      factor: 3
      writeQuorum: 2
  export:
    protocol: nfs
