apiVersion: novastor.io/v1alpha1
kind: StoragePool
metadata:
  name: ssd-erasurecoded
spec:
  nodeSelector:
    matchLabels:
      storage-tier: ssd
  backendType: raw
  deviceFilter:
    type: ssd
    minSize: "200Gi"
