apiVersion: novastor.io/v1alpha1
kind: StoragePool
metadata:
  name: nvme-replicated
spec:
  nodeSelector:
    matchLabels:
      storage-tier: nvme
  backendType: raw
  deviceFilter:
    type: nvme
    minSize: "100Gi"
