// Package v1alpha1 contains API Schema definitions for the novastor project.
// +k8s:deepcopy-gen:package,register
// nolint:revive // Auto-generated by controller-runtime and kubebuilder; comments are in GoDoc markers
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster
// +kubebuilder:printcolumn:name="Backend",type=string,JSONPath=`.spec.backendType`
// +kubebuilder:printcolumn:name="Nodes",type=integer,JSONPath=`.status.nodeCount`
// +kubebuilder:printcolumn:name="Capacity",type=string,JSONPath=`.status.totalCapacity`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// StoragePool defines a set of storage nodes and their backend configuration.
type StoragePool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              StoragePoolSpec   `json:"spec,omitempty"`
	Status            StoragePoolStatus `json:"status,omitempty"`
}

type StoragePoolSpec struct {
	// NodeSelector selects which nodes belong to this pool.
	NodeSelector *metav1.LabelSelector `json:"nodeSelector,omitempty"`

	// BackendType selects the storage backend for this pool.
	// - "file": File on existing mounted filesystem → SPDK AIO bdev
	// - "lvm": SPDK lvol store on unbound NVMe device (thin provisioning, snapshots)
	// - "raw": Direct SPDK NVMe bdev on unbound NVMe device (highest performance)
	// All backends produce SPDK bdevs consumed by the chunk engine.
	// +kubebuilder:validation:Enum=file;lvm;raw
	// +kubebuilder:default=lvm
	BackendType string `json:"backendType"`

	// DeviceFilter specifies which devices on selected nodes to use.
	// For "raw" and "lvm" backends, this selects NVMe devices to unbind and use.
	// For "file" backend, this is ignored (use FileBackend instead).
	DeviceFilter *DeviceFilter `json:"deviceFilter,omitempty"`

	// FileBackend configures the file backend. Only used when backendType is "file".
	FileBackend *FileBackendSpec `json:"fileBackend,omitempty"`
}

// FileBackendSpec configures the file backend (directory on existing filesystem).
type FileBackendSpec struct {
	// Path is the directory on each node where backing files are stored.
	// The directory must exist and be on a mounted filesystem.
	// +kubebuilder:default="/var/lib/novastor/file"
	Path string `json:"path"`

	// MaxCapacityBytes is the maximum size of the backing file per node.
	// Defaults to 80% of available filesystem space if not set.
	MaxCapacityBytes *int64 `json:"maxCapacityBytes,omitempty"`
}

type DeviceFilter struct {
	// +kubebuilder:validation:Enum=nvme;ssd;hdd
	Type    string `json:"type,omitempty"`
	MinSize string `json:"minSize,omitempty"`
}

type DataProtectionSpec struct {
	// +kubebuilder:validation:Enum=replication;erasureCoding
	Mode          string             `json:"mode"`
	Replication   *ReplicationSpec   `json:"replication,omitempty"`
	ErasureCoding *ErasureCodingSpec `json:"erasureCoding,omitempty"`
}

type ReplicationSpec struct {
	// +kubebuilder:default=3
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=5
	Factor      int `json:"factor"`
	WriteQuorum int `json:"writeQuorum,omitempty"`
}

type ErasureCodingSpec struct {
	// +kubebuilder:default=4
	// +kubebuilder:validation:Minimum=2
	DataShards int `json:"dataShards"`
	// +kubebuilder:default=2
	// +kubebuilder:validation:Minimum=1
	ParityShards int `json:"parityShards"`
}

type StoragePoolStatus struct {
	Phase         string             `json:"phase,omitempty"`
	NodeCount     int                `json:"nodeCount,omitempty"`
	TotalCapacity string             `json:"totalCapacity,omitempty"`
	UsedCapacity  string             `json:"usedCapacity,omitempty"`
	Conditions    []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
type StoragePoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StoragePool `json:"items"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Pool",type=string,JSONPath=`.spec.pool`
// +kubebuilder:printcolumn:name="Size",type=string,JSONPath=`.spec.size`
// +kubebuilder:printcolumn:name="Protection",type=string,JSONPath=`.spec.dataProtection.mode`
// +kubebuilder:printcolumn:name="Access",type=string,JSONPath=`.spec.accessMode`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

// BlockVolume represents a block storage volume.
type BlockVolume struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BlockVolumeSpec   `json:"spec,omitempty"`
	Status            BlockVolumeStatus `json:"status,omitempty"`
}

type BlockVolumeSpec struct {
	Pool string `json:"pool"`
	Size string `json:"size"`
	// +kubebuilder:validation:Enum=ReadWriteOnce;ReadOnlyMany
	AccessMode string `json:"accessMode"`
	// DataProtection configures how this volume's data is protected.
	DataProtection DataProtectionSpec `json:"dataProtection"`
	// Quota specifies an optional per-volume quota limit.
	// When set, the volume cannot grow beyond this size.
	// +optional
	Quota *int64 `json:"quota,omitempty"`
}

type BlockVolumeStatus struct {
	Phase      string             `json:"phase,omitempty"`
	Pool       string             `json:"pool,omitempty"`
	AccessMode string             `json:"accessMode,omitempty"`
	NodeID     string             `json:"nodeID,omitempty"`
	ChunkCount int                `json:"chunkCount,omitempty"`
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
type BlockVolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BlockVolume `json:"items"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Pool",type=string,JSONPath=`.spec.pool`
// +kubebuilder:printcolumn:name="Capacity",type=string,JSONPath=`.spec.capacity`
// +kubebuilder:printcolumn:name="Protection",type=string,JSONPath=`.spec.dataProtection.mode`
// +kubebuilder:printcolumn:name="Protocol",type=string,JSONPath=`.spec.export.protocol`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

// SharedFilesystem represents a shared filesystem.
type SharedFilesystem struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SharedFilesystemSpec   `json:"spec,omitempty"`
	Status            SharedFilesystemStatus `json:"status,omitempty"`
}

type SharedFilesystemSpec struct {
	Pool     string `json:"pool"`
	Capacity string `json:"capacity"`
	// +kubebuilder:validation:Enum=ReadWriteMany;ReadOnlyMany
	AccessMode string `json:"accessMode"`
	// DataProtection configures how this filesystem's data is protected.
	DataProtection DataProtectionSpec `json:"dataProtection"`
	Export         *ExportSpec        `json:"export,omitempty"`
	// Image overrides the NFS filer container image. Defaults to novastor/novastor-filer:v0.1.0.
	// +optional
	Image string `json:"image,omitempty"`
}

type ExportSpec struct {
	// +kubebuilder:validation:Enum=nfs
	Protocol string `json:"protocol"`
}

type SharedFilesystemStatus struct {
	Phase      string             `json:"phase,omitempty"`
	Endpoint   string             `json:"endpoint,omitempty"`
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
type SharedFilesystemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SharedFilesystem `json:"items"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Pool",type=string,JSONPath=`.spec.pool`
// +kubebuilder:printcolumn:name="Protection",type=string,JSONPath=`.spec.dataProtection.mode`
// +kubebuilder:printcolumn:name="Port",type=integer,JSONPath=`.spec.endpoint.service.port`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

// ObjectStore represents an S3-compatible object store.
type ObjectStore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ObjectStoreSpec   `json:"spec,omitempty"`
	Status            ObjectStoreStatus `json:"status,omitempty"`
}

type ObjectStoreSpec struct {
	Pool string `json:"pool"`
	// DataProtection configures how this object store's data is protected.
	DataProtection DataProtectionSpec `json:"dataProtection"`
	Endpoint       ObjectEndpointSpec `json:"endpoint"`
	BucketPolicy   *BucketPolicySpec  `json:"bucketPolicy,omitempty"`
	// Image overrides the S3 gateway container image. Defaults to novastor/novastor-s3gw:v0.1.0.
	// +optional
	Image string `json:"image,omitempty"`
}

type ObjectEndpointSpec struct {
	Service ObjectServiceSpec `json:"service"`
}

type ObjectServiceSpec struct {
	Port int32 `json:"port"`
}

type BucketPolicySpec struct {
	MaxBuckets int `json:"maxBuckets,omitempty"`
	// +kubebuilder:validation:Enum=enabled;disabled;suspended
	Versioning string `json:"versioning,omitempty"`
	// MaxBucketSize is the per-bucket storage quota in bytes.
	// When set, individual buckets cannot exceed this size.
	// +optional
	MaxBucketSize int64 `json:"maxBucketSize,omitempty"`
}

type ObjectStoreStatus struct {
	Phase      string             `json:"phase,omitempty"`
	Endpoint   string             `json:"endpoint,omitempty"`
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
type ObjectStoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ObjectStore `json:"items"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Pool",type=string,JSONPath=`.spec.poolRef`
// +kubebuilder:printcolumn:name="Node",type=string,JSONPath=`.spec.nodeName`
// +kubebuilder:printcolumn:name="Backend",type=string,JSONPath=`.spec.backendType`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Device",type=string,JSONPath=`.status.device`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// BackendAssignment binds a storage backend to a specific node for a StoragePool.
// Created by the StoragePool controller, provisioned by the node agent.
type BackendAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BackendAssignmentSpec   `json:"spec,omitempty"`
	Status            BackendAssignmentStatus `json:"status,omitempty"`
}

type BackendAssignmentSpec struct {
	// PoolRef is the name of the StoragePool this assignment belongs to.
	PoolRef string `json:"poolRef"`

	// NodeName is the node this assignment targets.
	NodeName string `json:"nodeName"`

	// BackendType is the backend type (copied from StoragePool).
	// +kubebuilder:validation:Enum=file;lvm;raw
	BackendType string `json:"backendType"`

	// DeviceFilter specifies which devices to use (copied from StoragePool).
	// For raw/lvm backends only.
	DeviceFilter *DeviceFilter `json:"deviceFilter,omitempty"`

	// FileBackend configures the file backend (copied from StoragePool).
	// For file backend only.
	FileBackend *FileBackendSpec `json:"fileBackend,omitempty"`
}

type BackendAssignmentStatus struct {
	// Phase is the provisioning state.
	// +kubebuilder:validation:Enum=Pending;Provisioning;Ready;Failed
	Phase string `json:"phase,omitempty"`

	// Device is the resolved device path (e.g., /dev/nvme0n1).
	Device string `json:"device,omitempty"`

	// PCIeAddr is the PCIe BDF address for NVMe devices.
	PCIeAddr string `json:"pcieAddr,omitempty"`

	// BdevName is the SPDK bdev name created on this device.
	BdevName string `json:"bdevName,omitempty"`

	// Capacity is the device capacity in bytes.
	Capacity int64 `json:"capacity,omitempty"`

	// Message provides details about the current phase (e.g., error details).
	Message string `json:"message,omitempty"`

	// Conditions represent the latest available observations.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
type BackendAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackendAssignment `json:"items"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Scope",type=string,JSONPath=`.spec.scope.kind`
// +kubebuilder:printcolumn:name="Scope Name",type=string,JSONPath=`.spec.scope.name`
// +kubebuilder:printcolumn:name="Storage Limit",type=string,JSONPath=`.spec.storage.hard`
// +kubebuilder:printcolumn:name="Used",type=string,JSONPath=`.status.storage.used`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

// StorageQuota defines storage consumption limits for a scope.
// Scopes can be namespaces (tenant-level), specific storage pools, or individual buckets.
type StorageQuota struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              StorageQuotaSpec   `json:"spec,omitempty"`
	Status            StorageQuotaStatus `json:"status,omitempty"`
}

type StorageQuotaSpec struct {
	// Scope defines the target of this quota.
	Scope QuotaScope `json:"scope"`

	// Storage defines storage limits.
	Storage *StorageQuotaSpecStorage `json:"storage,omitempty"`

	// ObjectCount defines object/bucket count limits.
	ObjectCount *ObjectCountQuotaSpec `json:"objectCount,omitempty"`
}

type QuotaScope struct {
	// +kubebuilder:validation:Enum=Namespace;StoragePool;Bucket;Volume
	Kind string `json:"kind"`

	// Name identifies the scope target.
	// For Namespace: the namespace name
	// For StoragePool: the pool name
	// For Bucket: the bucket name
	// For Volume: the volume ID
	Name string `json:"name"`
}

type StorageQuotaSpecStorage struct {
	// Hard is the hard limit in bytes. Requests exceeding this limit are rejected.
	Hard int64 `json:"hard"`

	// Soft is the soft limit in bytes. When exceeded, warnings are issued but requests are allowed.
	// +optional
	Soft int64 `json:"soft,omitempty"`
}

type ObjectCountQuotaSpec struct {
	// Hard is the hard limit for object/bucket count.
	Hard int64 `json:"hard"`
}

type StorageQuotaStatus struct {
	// Phase indicates the quota enforcement state.
	// +kubebuilder:validation:Enum=Active;Exceeded;Warning
	Phase string `json:"phase,omitempty"`

	// Storage reports storage usage.
	Storage *StorageQuotaStatusStorage `json:"storage,omitempty"`

	// ObjectCount reports object/bucket count usage.
	ObjectCount *ObjectCountQuotaStatus `json:"objectCount,omitempty"`

	// Conditions represent the latest available observations.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

type StorageQuotaStatusStorage struct {
	// Used is the current usage in bytes.
	Used int64 `json:"used,omitempty"`

	// UsedString is the current usage in human-readable format.
	UsedString string `json:"usedString,omitempty"`
}

type ObjectCountQuotaStatus struct {
	// Used is the current count.
	Used int64 `json:"used,omitempty"`
}

// +kubebuilder:object:root=true
type StorageQuotaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StorageQuota `json:"items"`
}
