// nolint:revive // Auto-generated deepcopy code
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function for BackendAssignmentSpec.
func (in *BackendAssignmentSpec) DeepCopyInto(out *BackendAssignmentSpec) {
	*out = *in
	if in.DeviceFilter != nil {
		in, out := &in.DeviceFilter, &out.DeviceFilter
		*out = new(DeviceFilter)
		**out = **in
	}
	if in.FileBackend != nil {
		in, out := &in.FileBackend, &out.FileBackend
		*out = new(FileBackendSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto is an autogenerated deepcopy function for BackendAssignmentStatus.
func (in *BackendAssignmentStatus) DeepCopyInto(out *BackendAssignmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function for StoragePoolSpec.
func (in *StoragePoolSpec) DeepCopyInto(out *StoragePoolSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceFilter != nil {
		in, out := &in.DeviceFilter, &out.DeviceFilter
		*out = new(DeviceFilter)
		**out = **in
	}
	if in.FileBackend != nil {
		in, out := &in.FileBackend, &out.FileBackend
		*out = new(FileBackendSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto is an autogenerated deepcopy function for FileBackendSpec.
func (in *FileBackendSpec) DeepCopyInto(out *FileBackendSpec) {
	*out = *in
	if in.MaxCapacityBytes != nil {
		in, out := &in.MaxCapacityBytes, &out.MaxCapacityBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopyInto is an autogenerated deepcopy function for StoragePoolStatus.
func (in *StoragePoolStatus) DeepCopyInto(out *StoragePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function for DeviceFilter.
func (in *DeviceFilter) DeepCopyInto(out *DeviceFilter) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for DataProtectionSpec.
func (in *DataProtectionSpec) DeepCopyInto(out *DataProtectionSpec) {
	*out = *in
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(ReplicationSpec)
		**out = **in
	}
	if in.ErasureCoding != nil {
		in, out := &in.ErasureCoding, &out.ErasureCoding
		*out = new(ErasureCodingSpec)
		**out = **in
	}
}

// DeepCopyInto is an autogenerated deepcopy function for ReplicationSpec.
func (in *ReplicationSpec) DeepCopyInto(out *ReplicationSpec) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for ErasureCodingSpec.
func (in *ErasureCodingSpec) DeepCopyInto(out *ErasureCodingSpec) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for BlockVolumeSpec.
func (in *BlockVolumeSpec) DeepCopyInto(out *BlockVolumeSpec) {
	*out = *in
	in.DataProtection.DeepCopyInto(&out.DataProtection)
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(int64)
		**out = **in
	}
}

// DeepCopyInto is an autogenerated deepcopy function for BlockVolumeStatus.
func (in *BlockVolumeStatus) DeepCopyInto(out *BlockVolumeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function for SharedFilesystemSpec.
func (in *SharedFilesystemSpec) DeepCopyInto(out *SharedFilesystemSpec) {
	*out = *in
	in.DataProtection.DeepCopyInto(&out.DataProtection)
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(ExportSpec)
		**out = **in
	}
}

// DeepCopyInto is an autogenerated deepcopy function for ExportSpec.
func (in *ExportSpec) DeepCopyInto(out *ExportSpec) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for SharedFilesystemStatus.
func (in *SharedFilesystemStatus) DeepCopyInto(out *SharedFilesystemStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function for ObjectStoreSpec.
func (in *ObjectStoreSpec) DeepCopyInto(out *ObjectStoreSpec) {
	*out = *in
	in.DataProtection.DeepCopyInto(&out.DataProtection)
	out.Endpoint = in.Endpoint
	if in.BucketPolicy != nil {
		in, out := &in.BucketPolicy, &out.BucketPolicy
		*out = new(BucketPolicySpec)
		**out = **in
	}
}

// DeepCopyInto is an autogenerated deepcopy function for ObjectEndpointSpec.
func (in *ObjectEndpointSpec) DeepCopyInto(out *ObjectEndpointSpec) {
	*out = *in
	out.Service = in.Service
}

// DeepCopyInto is an autogenerated deepcopy function for ObjectServiceSpec.
func (in *ObjectServiceSpec) DeepCopyInto(out *ObjectServiceSpec) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for BucketPolicySpec.
func (in *BucketPolicySpec) DeepCopyInto(out *BucketPolicySpec) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for ObjectStoreStatus.
func (in *ObjectStoreStatus) DeepCopyInto(out *ObjectStoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function for StorageQuotaSpec.
func (in *StorageQuotaSpec) DeepCopyInto(out *StorageQuotaSpec) {
	*out = *in
	out.Scope = in.Scope
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageQuotaSpecStorage)
		**out = **in
	}
	if in.ObjectCount != nil {
		in, out := &in.ObjectCount, &out.ObjectCount
		*out = new(ObjectCountQuotaSpec)
		**out = **in
	}
}

// DeepCopyInto is an autogenerated deepcopy function for QuotaScope.
func (in *QuotaScope) DeepCopyInto(out *QuotaScope) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for StorageQuotaSpecStorage.
func (in *StorageQuotaSpecStorage) DeepCopyInto(out *StorageQuotaSpecStorage) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for ObjectCountQuotaSpec.
func (in *ObjectCountQuotaSpec) DeepCopyInto(out *ObjectCountQuotaSpec) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for StorageQuotaStatus.
func (in *StorageQuotaStatus) DeepCopyInto(out *StorageQuotaStatus) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageQuotaStatusStorage)
		**out = **in
	}
	if in.ObjectCount != nil {
		in, out := &in.ObjectCount, &out.ObjectCount
		*out = new(ObjectCountQuotaStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function for StorageQuotaStatusStorage.
func (in *StorageQuotaStatusStorage) DeepCopyInto(out *StorageQuotaStatusStorage) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function for ObjectCountQuotaStatus.
func (in *ObjectCountQuotaStatus) DeepCopyInto(out *ObjectCountQuotaStatus) {
	*out = *in
}
