// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/metadata/metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetadataRequest is the envelope sent by clients for every metadata
// operation.
type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_api_proto_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *MetadataRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// MetadataResponse is the envelope returned by the server.
type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_api_proto_metadata_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metadata_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MetadataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_metadata_metadata_proto protoreflect.FileDescriptor

// Raw proto file descriptor encoded as a protobuf FileDescriptorProto.
// Built to match the .proto definition:
//
//	syntax = "proto3";
//	package metadata;
//	option go_package = "github.com/piwi3910/novastor/api/proto/metadata";
//	service MetadataService { rpc Execute(MetadataRequest) returns (MetadataResponse); }
//	message MetadataRequest { string operation = 1; bytes payload = 2; }
//	message MetadataResponse { bytes payload = 1; string error = 2; }
const file_api_proto_metadata_metadata_proto_rawDesc = "" +
	"\n!api/proto/metadata/metadata.proto\x12\bmetadata\x22I\n\x0f" +
	"MetadataRequest\x12\x1c\n\toperation\x18\x01 \x01(\tR\toperat" +
	"ion\x12\x18\n\x07payload\x18\x02 \x01(\x0cR\x07payload\x22B\n" +
	"\x10MetadataResponse\x12\x18\n\x07payload\x18\x01 \x01(\x0cR\x07" +
	"payload\x12\x14\n\x05error\x18\x02 \x01(\tR\x05error2S\n\x0fM" +
	"etadataService\x12@\n\x07Execute\x12\x19.metadata.MetadataReq" +
	"uest\x1a\x1a.metadata.MetadataResponseB1Z/github.com/piwi3910" +
	"/novastor/api/proto/metadatab\x06proto3"

var (
	file_api_proto_metadata_metadata_proto_rawDescOnce sync.Once
	file_api_proto_metadata_metadata_proto_rawDescData []byte
)

func file_api_proto_metadata_metadata_proto_rawDescGZIP() []byte {
	file_api_proto_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_api_proto_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_metadata_metadata_proto_rawDesc), len(file_api_proto_metadata_metadata_proto_rawDesc)))
	})
	return file_api_proto_metadata_metadata_proto_rawDescData
}

var file_api_proto_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_metadata_metadata_proto_goTypes = []any{
	(*MetadataRequest)(nil),  // 0: metadata.MetadataRequest
	(*MetadataResponse)(nil), // 1: metadata.MetadataResponse
}
var file_api_proto_metadata_metadata_proto_depIdxs = []int32{
	0, // 0: metadata.MetadataService.Execute:input_type -> metadata.MetadataRequest
	1, // 1: metadata.MetadataService.Execute:output_type -> metadata.MetadataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_metadata_metadata_proto_init() }
func file_api_proto_metadata_metadata_proto_init() {
	if File_api_proto_metadata_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_metadata_metadata_proto_rawDesc), len(file_api_proto_metadata_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_api_proto_metadata_metadata_proto_depIdxs,
		MessageInfos:      file_api_proto_metadata_metadata_proto_msgTypes,
	}.Build()
	File_api_proto_metadata_metadata_proto = out.File
	file_api_proto_metadata_metadata_proto_goTypes = nil
	file_api_proto_metadata_metadata_proto_depIdxs = nil
}
